### ISSUE TITLE
BG bug with party roles

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#100]
Political parties in ParlaMint are supposed to be marked as `org[@role='politicalParty']` or `org[@role='politicalGroup']` (if they are lists of political parties belonging to the parliament). However, there are two parties in BG that are marked as "coalition":
```
<org role="coalition" xml:id="party.BSPBG">
   <orgName full="yes" xml:lang="bg">БСП за България</orgName>
   <orgName full="yes" xml:lang="en">Coalition for Bulgaria</orgName>
```
and
```
<org role="coalition" xml:id="party.PATR">
   <orgName full="yes" xml:lang="bg">Обединени патриоти</orgName>
   <orgName full="yes" xml:lang="en">United Patriots</orgName>
```

This has the unfortunate consequence that in the vertical files (and concordancers) the people that belong to these parties are not marked as belonging to any party.

Also, it is not an easy bug to fix: if these two are true coallitions, then they should not be in the organisation list at all, as we encode coalitions differently, with relations. So, all the speakers belonging to these "coalitions" should in fact belong to one of the parties that are a part of them.

**Comment by matyaskopp** [comment]
I think that we should distinguish two types of coalitions in our encoding:

1. **true coalition** - multiple parties are elected together (they belong to this coalition for the whole term )
2. **government coalition** - can be changed during a term and can even contain _true coalition_

In the manner of Czech understanding. I think that a "politicalGroup" would represent the _true coalition_, so no one cares that it is not a politicalParty.

But BG does not have political groups, so my doubtful suggestion is to use "politicalCoalition".

**Comment by osenova** [comment]
Both 'coalitions' are actually 'internal' ones, i.e. both of them consist of several parties that united in order to pass the elections barrier. It seems they are _true coalitions_ although during the ruling there was a party from PATR that left it.
I see that the problem is in the encoding. We should change this to **politicalGroup** for the next version.

**Comment by TomazErjavec** [comment]
Yes, I agree from what I understand from the above: party.BSPBG and party.PATR should be "politicalGroup", I would not introduce another type of party grouping, unless there are very persuasive reasons to do so. Note also that the coalition/oppositions lists should be fixed, as now they don't make reference to BSPBG and PATR:. 
https://github.com/clarin-eric/ParlaMint/blob/8484b5e072976db8e36e029436df9c38ff7e3694/ParlaMint-BG/ParlaMint-BG.xml#L512-L533
(and also .ana of course).

**Comment by osenova** [comment]
Hi again, Tomaz and Matyas,
I would like we to fix this bug. So, how exactly this should happen? Is there a version where we can change directly the coalition value to politicalGroup for the affected political groups, or we should do this locally in our files and then commit? Apologies if it is obvious but I cannot  see it...Thanks!!!!

**Comment by matyaskopp** [comment]
> We should change this to **politicalGroup** for the next version.

>Yes, I agree from what I understand from the above: party.BSPBG and party.PATR should be "politicalGroup", I would not introduce another type of party grouping, unless there are very persuasive reasons to do so.

I am afraid, that I don't agree. As I see it `party.BSPBG` and  `party.PATR` should be `politicalParty`:

1. BG do not introduce `politicalGroup` so why now
2. There will be a mixture of political parties and groups in parliament. (ie. CZ data have only political groups in parliament. Political parties are defined independently on parliament)
3. `politicalGroup` is defined on the parliament ground and correspond to a single term. A new term has to define new political groups.

If there is a possibility of divorcing political parties that went to election together (to pass the barrier), then `politicalGroup` should be introduced and I would encode the situation in this way:

- parties P1 and P2 goes to election together
  - `<org role="politicalParty" xml:id="COALITION_PARTY">...` 
- registered political party
  - `<org role="politicalParty" xml:id="P1">...`
  - `<org role="politicalParty" xml:id="P2">...`
- groups of MP tat corresponds to political parties in the election
  - `<org role="politicalGroup" xml:id="G1">...`
  - `<org role="politicalGroup" xml:id="G2">...`
- relations
  - P1 and P2 can decide to continue cooperation in parliament  so their representants G1 and G2 form a coalition. 
    They are both in government case:  `<relation name="coalition" active="#G1 #G2"    passive="#GOV" from="DATE1"  ana="#TERM1"/> `
  - After a while they can sop the cooperation so `//relation/@to` is set to that time


> I would like we to fix this bug. So, how exactly this should happen? Is there a version where we can change directly the coalition value to politicalGroup for the affected political groups, or we should do this locally in our files and then commit? Apologies if it is obvious but I cannot see it...Thanks!!!!

So there are two solutions:

1. if it is not possible that parties will not divorce during the term -> you can consider them as a single party and don't define their relation
2. if the divorce is possible, I am afraid that `politicalGroup` should be introduced -> so now **do nothing**, because it is only my opinion and it needs more discussion with @TomazErjavec

**Comment by matyaskopp** [comment]
https://github.com/clarin-eric/ParlaMint/issues/100#issuecomment-894485010:
> In the manner of Czech understanding. I think that a "politicalGroup" would represent the true coalition, so no one cares that it is not a politicalParty.

Oh, I have looked above to my previous answer. After our autumn election, it seems that I am not consistent with myself.
I did not fully consider the possibility of divorce. So my current opinion is that the true coalition should be a `politicalParty` if we don't want to introduce a new role.

**Comment by osenova** [comment]
Thanks, Matyas! I think I have two possibilities:
- I can change them to **politicalParty** (that presumably and recursively consists of other political parties)
- I can just get rid of these two labels, and live only with the parties that go inside these.
When we all have consensus what is best, I need to know where we should introduce these changes.

**Comment by matyaskopp** [comment]
> - I can just get rid of these two labels, and live only with the parties that go inside these.

This option sounds good to me - it simplifies the situation. So to conclude my opinion:

- We care only about the situation that is on the parliament ground.  
- We ignore that multiple parties are on the same ballot paper.
- After the election, the parties decide if they are 
  - together in `oposition`/`coalition` with the respect of government
  - separated

> When we all have consensus what is best, I need to know where we should introduce these changes.

Currently, I am not able to answer this question. 
Adding coalitions was a hotfix in ParlaMint 2.1, so @TomazErjavec did it himself to avoid bugs and make it faster. In the next version, I think every partner should add their `oposition`/`coalition` relations themself, but this decision is not only up to me. 
So please give us a while to make the right decision.

**Comment by osenova** [comment]
Thanks again, Matyas! Of course, please do not get me wrong, take your time. :) I just wanted to be sure that I have not missed anything we were supposed to do ourselves in the data.

**Comment by KirilSimov** [comment]
Thank you for the remarks! Now I am in and in the next days we will update the header and we will check all the data in it.
Also we will add the data for the other sessions of the parliament.

Kiril

**Comment by TomazErjavec** [comment]
I didn't actually check @osenova, @KirilSimov, but is this fixed now, i.e. can we close this issue?

**Comment by TomazErjavec** [comment]
This seems to have been fixed, thank you and closing!
