### ISSUE TITLE
SI: Lemmas for hyphenated words are wrong 

### ISSUE THREAD

**Issue by ajdapretnar** [clarin-eric/ParlaMint#102]
Lemmas for hyphenated words replace the hyphen with a "v".
I.e. "gozdno-lesen" --> "gozdnovlesen" (see document ParlaMint-SI_2020-06-15-SDZ8-Redna-18).

This is a common occurrence in the Slovenian corpus. Don't know how to check for others.

**Comment by nljubesi** [comment]
The reason for this bug is technology + training data. We (stanza actually, we are not that smart) use seq2seq for lemmatization of unknown words and in ssj500k (training data) there are only 5 occurrences of `[word=".+-.+" & lemma=".+-.+"]` and 15 occurrences of `[word=".+-.+" & lemma!=".+-.+"]`. "Garbage" (non-representativeness) in, garbage out.

Another problem is, as expected, that in the training data the hyphenation problem is infrequent (25 per million), while in parliamentary data it is  very frequent (865 per million). All you need for a disaster.

In Croatian (et al.) we do not have this problem as the hyphenation phenomenon is very frequent in the training data. The `[word=".+-.+" & lemma=".+-.+"]` occurrs 1,080 times, and the training data is of similar size to the Slovenian ones.

I do not see a way of improving this for ParlaMint, except by performing a post-processing step. I hope that the new Slovenian training data will have more of such hyphenation examples. Can this be checked somewhere (is the dataset already available)? If it shows that there are no hyphenations in the new Slovenian dataset, this should probably be dealt with before the publication of the dataset.

**Comment by nljubesi** [comment]
We had a discussion on this hyphen issue on another channel and, thanks to Kaja Dobrovoljc, we realized that now classla knows how to deal with hyphenated words. While we were processing ParlaMint data, classla was still using, for the Slovenian standard language mode, a tokenizer that does not agree with the ssj500k training data.

I guess this issue will be dealt with in the follow-up project by reprocessing all the data with classla. We improved classla in the meantime on other fronts as well (function words control via inflectional lexicon, punctuation control via tokenizer).

I consider this dealt with. If not, please reopen.
