### ISSUE TITLE
Hierarchical structure of organizations

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#11]
There are various types of organizations in our (CZ) parliament data, eg: committee, subcommittee, workingGroup, politicalGroup, government.
And they have a hierarchical structure of `org`. Would be possible to allow `//org/listOrg/org`?

**Comment by TomazErjavec** [comment]
We model such relations in the parla.legislature taxonomy cf. https://github.com/clarin-eric/ParlaMint/blob/main/ParlaMint-SI/ParlaMint-SI.xml#L96

This is quite an important taxonomy, and everybody should have (as well as the other ones) it in their corpus header, and refer to it from the appropriate places, esp. the meeting elements in the component files teiHeader/fileDesc/titleStmt.

**Comment by matyaskopp** [comment]
ok, I will flatten organizations and remove parent organizations with no affiliated person.

Do we have to use the identical taxonomy? Or can we extend it with our own categories?
For example, we divide files into topics (agenda items) and use `#parla.agenda` for annotating such files.

**Comment by TomazErjavec** [comment]
> Do we have to use the identical taxonomy? Or can we extend it with our own categories?

Ideally we would all have identical taxonomies, which could model the organisation of the pairlament regardless of the country. But this is not the case even now, so, yes, you can change it, but it would be nice if yours were an extension, rather than a destructive change. 

> For example, we divide files into topics (agenda items) and use #parla.agenda for annotating such files.

OK, but I would say that parla.agenda is a different taxonomy from parla.legislature, its like apples and pears.

**Comment by TomazErjavec** [comment]
I guess we can close this now @matyaskopp, right? If not, pls. reopen.
