### ISSUE TITLE
cleanup: <tab> / <spaces>

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#113]
I am suggesting doing a minor Xmas code cleanup.
There are instances in using spaces and tabs indentations in code:

- samples are using saxon default 3-spaces indentation [`//@saxon:indent-spaces`](https://www.saxonica.com/documentation9.5/extensions/output-extras/indent-spaces.html)
- XSLT and Perl scripts use a mixture of (8-spaces big) `<TAB>s` and 4-spaces identation;
![image](https://user-images.githubusercontent.com/5867995/146940364-abe3cfde-23ba-491d-8df7-cf25a73933e2.png)

@TomazErjavec, do you insist on this state? 
Or can I replace `<TAB>s` with 8 spaces and set `//@saxon:indent-spaces=4`?

**Comment by TomazErjavec** [comment]
> @TomazErjavec, do you insist on this state?

Well, the "four spaces or TAB" is what emacs does when I am editing Perl files, and "two spaces or TAB" for XML (incl. xslt) files.  I tried fiddling with this in my .emacs, but with limited sucess, it is all rather scary and I am not sure if it works so that it never outputs TABs and has always indent 3. But I hope so.

However, what is really the point of this? It can make for problematic diffs, but it seems you can switch this off in GitHub (https://github.blog/2018-05-01-ignore-white-space-in-code-review/)? 

Anyway, if you wish, you can prettify the spaces, and in case my new .emacs fails, you can shout at me, and I can try again to modify it. 

For the record, this is what I now have in .emacs:

```
;; Doesn't work for me, throws an error on require:
;; indentation using smart-tabs-mode
;; (add-to-list 'load-path "~/.emacs.d/smart-tab.el")
;; (setq-default tab-width 3)
;; (require 'smart-tab)
;; (global-smart-tab-mode 1)
;; (smart-tabs-insinuate 'cperl 'perl 'nxml)

;; set nxml-mode indents, so they match Saxon's
(setq
    nxml-child-indent 3
    nxml-attribute-indent 4
    nxml-slash-auto-complete-flag t)

;; Global settings:
(setq-default indent-tabs-mode nil)
(setq-default tab-width 3)
(setq indent-line-function 'insert-tab)
```

**Comment by matyaskopp** [comment]
The point was that I was afraid of making a mess with different indentation habits...

I will adapt myself to your rules.
