### ISSUE TITLE
Are ParlaMint{.xml,.ana.xml} files valid?

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#154]
[ParlaMint.xml](https://github.com/clarin-eric/ParlaMint/blob/main/Data/ParlaMint.xml) and [ParlaMint.ana.xml](https://github.com/clarin-eric/ParlaMint/blob/main/Data/ParlaMint.ana.xml) files do not seem to be valid because  `@xml:id` is not unique among all corpora.
It is possible to have `teiCorpus/teiCorpus` (see https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-teiCorpus.html). So probably only unique IDs should be managed.

**Comment by TomazErjavec** [comment]
We can't make the IDs unique across corpora, as we have e.g. the taxonomies, which we want to unify, which also means their categories will have the same IDs.

However, I see now that teiCorpus can also have text as its child (https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-teiCorpus.html) which would solve the problem in the way in which you already suggested. So, instead of 
```
   <xi:include xmlns:xi="http://www.w3.org/2001/XInclude"
               href="ParlaMint-BE/ParlaMint-BE.ana.xml"/>
   <xi:include xmlns:xi="http://www.w3.org/2001/XInclude"
               href="ParlaMint-BG/ParlaMint-BG.ana.xml"/>
```
we would have something like
```
<text>
  <body>
    <p>The information in this TEI header has been automatically collected from:
      <list>
         <item><ref target="ParlaMint-BE/ParlaMint-BE.ana.xml">ParlaMint-BE/ParlaMint-BE.ana.xml</item>
         <item><ref target="ParlaMint-BG/ParlaMint-BG.ana.xml">ParlaMint-BG/ParlaMint-BG.ana.xml</item>
      </list>
  </body>
</text>
```
Of course, it would still be a good idea to change the name of the two files, so people aren't confused. Maybe even move the to the Metadata/ directory, as they essentially copy the metadata from the individual corpora.

What do you think?

**Comment by matyaskopp** [comment]
It sounds good. 
Probably we can use `TEI` instead of `teiCorpus` and say: this is a TEI file that contains metadata from our corpus files. 

Only strange thing is that e.g.`tagUsage` should describe the content of the file but it is not true in this composition. But I don't see better solution...

**Comment by TomazErjavec** [comment]
Thinking some more about this, I would suggest we should leave it as it is because this is a clean solution, except, of course, that the document has duplicate IDs. But even here, most likely things that have the same ID also have more or less the same content.

Because, if we change the way I sugested, then, as you point out, the teiHeader does not in fact describe the content of the document, and if we were to change to the TEI top level element, it gets even more messy; what we should have then in some sort of summary in the body of the TEI, and not anymore in its header.

But, yes, it would be a good idea to change the names to, say ParlaMint-summary.xml or something like that.

**Comment by TomazErjavec** [comment]
I've now simply added a note on ID conflicts in the title of the generated corpora.
Also fixed Makefile and script so it works with the move of the corpora to Data, and some other changes, cf. 6f5fe8a
If you agree with this, pls. merge into main and close.

**Comment by matyaskopp** [comment]
Should I change the filename? 
Your suggestion `ParlaMint-summary{,.ana}.xml` sounds good to me.

**Comment by TomazErjavec** [comment]
Given the title that admits it is not a valid XML doc, I don't think it is necessary. But, if you think otherwise, sure, change it. I am agnostic.

**Comment by matyaskopp** [comment]
OK, leaving it as is and closing issue...
