### ISSUE TITLE
Better schemaSpecs in the ParlaMint ODD

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#164]
The [documentation on the ParlaMint encoding](https://clarin-eric.github.io/ParlaMint/) is more or less finished. But this is a TEI ODD file, and also includes the [ODD schema specification](https://github.com/clarin-eric/ParlaMint/blob/documentation/TEI/ParlaMint-schemaSpecs.odd.xml). It would be very hard to make it as constrained as our [bespoke schemas](https://github.com/clarin-eric/ParlaMint/tree/documentation/Schema), but it would still be good to make it as tight as possible, not the least so that its documentation on [GitHub pages ](https://clarin-eric.github.io/ParlaMint/#schema) lists only the attributes that are in fact allowed for a particular element.

I have modified the definitions of about 10 elements, e.g. the top level ones, and the linguistic ones, e.g. [s](https://clarin-eric.github.io/ParlaMint/#TEI.s). However:

- I think the modifications could be done better than I did them, like without the listing all the attributes that are not allowed for each and every element, for example for [TEI](https://github.com/clarin-eric/ParlaMint/blob/22caea04716aa7b47f368c0a4f8ce072fe2164cc/TEI/ParlaMint-schemaSpecs.odd.xml#L152-L162). 
- I did about 10 elements, but there are over 100 to define, so lots of manual work
- the specifications could (and probably should) also contain ParlaMint specific description (desc), examples (exemplum) and notes (remarks) for each element, rather than default TEI ones

So, this issue is here to note that these things still need to be done, and as a plea for help (esp. @matyaskopp)

**Comment by matyaskopp** [comment]
The ODD schema specification development is very cyclic. If you decide to add a new attribute you have to check all places when the attribute appears and remove it.

i.e. `@decls` from [arr.declaring](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.declaring.html):
https://github.com/clarin-eric/ParlaMint/blob/aa93282dcdd321fca2d9d7f9cd31fbd11d4bb75a/TEI/ParlaMint-schemaSpecs.odd.xml#L34
-> `<classRef key="att.declaring" include="decls"/> `
Then you have to check all elements that attributes from `arr.declaring` class use, e.g. `<u>`, and add there a line:
```
      <attDef ident="decls" mode="delete"/>
```

I tried to find a better solution: 
- e.g. we know that element `<u>` do not use attributes from `att.declaring` class so we will set that the attributes from this class will not be used never more. But schemaSpec does not allow this.
- It is possible to use `elementSpec/@mode='replace'`, but it removes/replaces the whole definition of the element. It is a pity that `@mode` is not defined for `attList`, we want to replace only attributes.

@TomazErjavec , what do you think about "extending" schemaSpec with a new element
```
<pm:attPreserveList>
  <pm:attPreserve class="att.declaring" name="decls" />
</pm:attPreserveList>
```
and then run transformation, which will produce `attList` in order to produce the proper schema. I did not think about it in-depth, it is just a first idea.

**Comment by matyaskopp** [comment]
I have started with implementation: https://github.com/clarin-eric/ParlaMint/pull/171

**Comment by TomazErjavec** [comment]
> what do you think about "extending" schemaSpec with a new element

I think that this complicates things, i.e. if no other way can be found, I'd actually be in favour of adding the deleted attribtues by hand (they are pretty repetitive) as I already did for the first 10 or so elements. Alternativelly, and maybe better, as you write

> It is possible to use elementSpec/@mode='replace', but it removes/replaces the whole definition of the element

we could just use this, given how constrained our schema is. So, we would simply redefine all elements and get as good a fit as possible.

That said, and given that you already started implementing your solution, you could go ahead with this, except that I would suggest that rather than having ParlaMint-schemaSpecs.odd.xml and ParlaMint-schemaSpecs.generated.odd.xml we would have ParlaMint-schemaSpecs.editing.odd.xml and ParlaMint-schemaSpecs.odd.xml, i.e. the "official" schema specs would be the generated one, and the "editing" one for, well, editing.

**Comment by matyaskopp** [comment]
> That said, and given that you already started implementing your solution, you could go ahead with this, except that I would suggest that rather than having ParlaMint-schemaSpecs.odd.xml and ParlaMint-schemaSpecs.generated.odd.xml we would have ParlaMint-schemaSpecs.editing.odd.xml and ParlaMint-schemaSpecs.odd.xml, i.e. the "official" schema specs would be the generated one, and the "editing" one for, well, editing.

Ok, I will make all modifications in [schemaSpec-generate](https://github.com/clarin-eric/ParlaMint/tree/schemaSpec-generate) branch. I think that this is a faster and more foolproof solution.

**Comment by TomazErjavec** [comment]
The shemaSpecs in the ODD are as good as they are likely to get, so, closing.
