### ISSUE TITLE
schemaSpecs: idno type attribute values

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#173]
related to: https://github.com/clarin-eric/ParlaMint/issues/59, https://github.com/clarin-eric/ParlaMint/issues/68

There is still a mess in `<idno>` element `@type` and `@subtype` attributes. Sample data `idno` variations (removed `@xml:lang` and sorted `@type` and `@subtype`):
```
grep -ro '<idno [^>]*>' Data/ParlaMint-*/ |sed -n "s/^Data\/ParlaMint-\([-A-Z]*\)\/.*xml:</\1\t</p" | sed 's/ xml:lang="[a-z]*"//'|sed 's/\(subtype="[^"]*"\)\s\s*\(type="[^"]*"\)/\2 \1/'|sort|uniq -c 
     12 BE	<idno type="URI">
     10 BE	<idno type="URI" subtype="handle">
      4 BE	<idno type="wikimedia">
     10 BG	<idno type="URI">
      8 BG	<idno type="URI" subtype="handle">
    322 BG	<idno type="URI" subtype="wikimedia">
      4 BG	<idno type="url">
    954 CZ	<idno type="URI">
     46 CZ	<idno type="URI" subtype="facebook">
     18 CZ	<idno type="URI" subtype="personal">
     10 CZ	<idno type="URL">
      8 DK	<idno type="URI">
      8 DK	<idno type="URI" subtype="handle">
      4 DK	<idno type="wikimedia">
     10 ES	<idno type="URI">
     10 ES	<idno type="URI" subtype="handle">
      8 ES	<idno type="URI" subtype="wikimedia">
     12 FR	<idno type="URI">
      8 FR	<idno type="URI" subtype="handle">
      8 GB	<idno type="URI">
   3802 GB	<idno type="URI" subtype="contact">
    324 GB	<idno type="URI" subtype="facebook">
      8 GB	<idno type="URI" subtype="handle">
   1608 GB	<idno type="URI" subtype="twitter">
     16 HR	<idno type="URI">
      8 HR	<idno type="URI" subtype="handle">
      4 HR	<idno type="URI" subtype="wikimedia">
      8 HU	<idno type="URI">
      8 HU	<idno type="URI" subtype="handle">
      2 HU	<idno type="URI" subtype="wikimedia">
      2 HU	<idno type="wikimedia">
      8 IS	<idno type="URI">
      8 IS	<idno type="URI" subtype="handle">
    410 IS	<idno type="URL">
   1714 IT	<idno type="senato.it">
     10 IT	<idno type="URI">
     10 IT	<idno type="URI" subtype="handle">
      8 IT	<idno type="wikimedia">
      8 LT	<idno type="URI">
      8 LT	<idno type="URI" subtype="handle">
      4 LT	<idno type="wikipedia">
     10 LV	<idno type="URI">
      1 LV	<idno type="URI" subtype="handle"/>
      9 LV	<idno type="URI" subtype="handle">
      4 LV	<idno type="wikimedia">
     10 NL	<idno type="URI">
      8 NL	<idno type="URI" subtype="handle">
      8 NL	<idno type="wikimedia">
     10 PL	<idno type="URI">
      8 PL	<idno type="URI" subtype="handle">
      8 SI	<idno type="URI">
      8 SI	<idno type="URI" subtype="handle">
    224 SI	<idno type="URI" subtype="wikimedia">
      8 TR	<idno type="URI">
      8 TR	<idno type="URI" subtype="handle">
     38 TR	<idno type="wikidata">
     78 TR	<idno type="wikimedia">
```

Do we want to fix this inconsistency and push the following countries: 

```
      4 BE	<idno type="wikimedia">
      4 BG	<idno type="url">
     10 CZ	<idno type="URL">
      4 DK	<idno type="wikimedia">
      2 HU	<idno type="wikimedia">
    410 IS	<idno type="URL">
   1714 IT	<idno type="senato.it">
      8 IT	<idno type="wikimedia">
      4 LT	<idno type="wikipedia">
      4 LV	<idno type="wikimedia">
      8 NL	<idno type="wikimedia">
     38 TR	<idno type="wikidata">
     78 TR	<idno type="wikimedia">
```
to fix it in this way?
 `<idno type="wikimedia">`  to  `<idno type="URI" subtype="wikimedia">` 
 `<idno type="wikipedia">`   to  `<idno type="URI" subtype="wikipedia">`
 `<idno type="wikidata">`     to  `<idno type="URI" subtype="wikidata">`
 `<idno type="url">`              to  `<idno type="URI">`    
 `<idno type="URL">`           to  `<idno type="URI">`   
 `<idno type="senato.it">`     to  `<idno type="URI">`

**Comment by matyaskopp** [comment]
> Except, I don't see GB in your list, even though they have `<idno type="URI" subtype="contact">`. 

I am not sure if it should be fixed. I think that `@subtype` can contain identification of organization that's URL is stored in text value:
- wikipedia
- wikimedia
- wikidata
- facebook
- twitter
- tiktok
- instagram
- ...

OR there is a country-specific organization (government, parliament, political party), so less specific values can be used:
- government
- parliament

OR URL points to personal web:
- personal
- contact
- profile

I am not sure which values should we admin (definitely not all of them) - these lists are for demonstration of idea.
If we use these values the IT case(`<idno type="senato.it">`) will be fixed: `<idno type="URI" subtype="parliament">` or more specific:  `<idno type="URI" subtype="senate">`

> I guess this should go to simple `<idno type="URI">`.

It is ok, but whenever we can be more concrete and use `@subtype` then we should do that.

> Would this be one more job for finalise?

No. Finalize script shouldn't clean the mess. We can provide an XSLT script that can be easily modified to fix these issues, but I don't think embedding it into finalization is a good idea.

**Comment by TomazErjavec** [comment]
Thanks for providin a neat list of possible values. I almost agree with what you write, except that 
* GB `<idno type="URI" subtype="contact">` is a governmental URL for the MP, so really not much different from e.g. the IT one
* I think your list more or less exhausts the possibilites for social media platforms, i.e. no need for the "..."
* I would slightly simplfy/constrain the possible governmental pages (now "contact", "senate", "government", "parliament"), I think they all boil down to "government" really, i.e. if somebody has one of these, they won't have another, and it is not relevant which one it is (we have better ways of determining if somebody is in the senate as opposed to the parliament).

So, with this, we could have the following list, which I'd suggest we enforce in the schema for idno/@subtype:

* government, politicalParty
* personal, business
* wikipedia, wikimedia, wikidata, facebook, twitter, tiktok, instagram

@matyaskopp, would you agree?

> Finalize script shouldn't clean the mess. We can provide an XSLT script that can be easily modified to fix these issue

OK, but I think we do need the XSLT script to fix current issues (probably not just for this subtype), so we can have valid samples.  Maybe `fix-fv2tov3.xsl` or something.

**Comment by matyaskopp** [comment]
Ok, it was more like a brain dump. It was not meant as a final/correct list.

> So, with this, we could have the following list, which I'd suggest we enforce in the schema for idno/@subtype:
>
> - government, politicalParty
> - personal, business
> - wikipedia, wikimedia, wikidata, facebook, twitter, tiktok, Instagram

Agree, I will integrate it into odd schema

> OK, but I think we do need the XSLT script to fix current issues (probably not just for this subtype), so we can have valid samples. Maybe fix-fv2tov3.xsl or something.

Ok, a new issue is needed with the list of all fixes.

**Comment by matyaskopp** [comment]
I am adding one more value:
- government, politicalParty, **parliament**
- personal, business
- wikipedia, wikimedia, wikidata, facebook, twitter, tiktok, Instagram

I want to categorize profile pages that are listed on the parliamentary website (not the government)

**Comment by matyaskopp** [comment]
As most corpora use `@subtype=wikimedia`  for wiki**p**edia links I think we can merge `wikipedia`+`wikimedia`+`wikidata` to one subtype: `wikimedia`. So the final list is:
- government, politicalParty, parliament
- personal, business
- ~~wikipedia,~~ wikimedia, ~~wikidata,~~ facebook, twitter, tiktok, Instagram

**Comment by TomazErjavec** [comment]
> I want to categorize profile pages that are listed on the parliamentary website (not the government)

OK, although I don't see much of a difference, but if you do, so be it!
I also agree with wikimedia, so that we now have:

*   government, politicalParty, parliament
*   wikimedia, facebook, twitter, tiktok, Instagram
*   personal, business

One thing though: we have politicalParty and politicalGroup orgs, but only politicalParty for the web pages. But I think this is ok, it would be really obsessive to distinghish the two for web pages.

**Comment by TomazErjavec** [comment]
One more thing, related to #187: this would then also need to be corrected to `<idno type="URI" subtype="parliament">https://www.althingi.is/</idno>`, i.e. any `sourceDesc/bibl/idno` by definition gets this subtype.
Probably relevant for #173.

**Comment by matyaskopp** [comment]
The patch is implemented in 
https://github.com/clarin-eric/ParlaMint/blob/eaa6f21ab666f363616b80ffa438cf0b71a84ecd/Scripts/fixings/v2tov3/v2tov3.xsl#L158-L161

But I can imagine that someone wants to have also Wikipedia in bibl in order to get personal data of MP or should `bibl` contain only the source of text?

**Comment by TomazErjavec** [comment]
My point was that here you could make a patch regardless of the corpus, just based on the context of the idno - but see below. And, probably the source description should be of the text only, otherwise it will get messy. Although it is true, that the metadata will have a source or even sources too, hm. 

But I now went through all the source descriptions below, and there are some outliers:
* NL gives the URLs of the upper and lower house, but I guess they are both "parliament".
* BG and HR give the URLs of Parlameter (from where they got the data) and the official parliament web site. We have a problem: what subtype to give the Parlameter site?

Maybe we should insist on subtype only for those `idno`s under `person` or `org`? And forget sourceDesc? Not sure myself...

https://github.com/clarin-eric/ParlaMint/blob/5d0a3ba86af5818285e065e35081be62f6814c6b/Data/ParlaMint.xml#L404-L568

**Comment by matyaskopp** [comment]
> OK, although I don't see much of a difference, but if you do, so be it!
I also agree with wikimedia, so that we now have:
> - government, politicalParty, parliament
> - wikimedia, facebook, twitter, tiktok, Instagram
> - personal, business

I am adding two more roles if @TomazErjavec  agrees:
 - government, politicalParty, parliament, **ministry**, **publicService**
 - wikimedia, facebook, twitter, tiktok, Instagram
 - personal, business

**ministry** is reserved for ministries
and **publicService** for other public service institutions (opposite to business) - for courts, schools, healthcare,..

**Comment by TomazErjavec** [comment]
OK, the current list of subtypes by @matyaskopp seems to be:
* government, politicalParty, parliament, ministry, publicService
* wikimedia, facebook, twitter, tiktok, Instagram
* personal, business

My comments:
* we also need "handle"
* wouldn't it be sensible to distinguish wikipedia from wikidata, they are very different; if there is nothing else under "wikimedia" I would suggest having these two instead of wikimedia
* e.g. ParlaMeter web site does not belong to a bussiness, but to a NGO; should be rather have "organisation" instead of "bussiness"? Or both? Or should ParlaMeter be "publicService"? It gets confusing...
* do we really need all the social media explicitly listed? There's bound to be some new ones, and if we want a closed list, we will have to keep adding to it. I'd suggest "socialMedia" instead of facebook, twitter, tiktok, instagram. Presumably they can be disambiguated by URL. This is just a suggestion, maybe it is better to have them listed.

I've now added @matyaskopp suggested values to the ODD schemaSpecs, also made the list closed. Pls. have a [look](https://clarin-eric.github.io/ParlaMint/#TEI.idno) and let me know if you agree with the explanations, and also the the comments above. Once we have this fixed, I can do the same in the RNG schemas. However, this brings with it the question if we want to change the schema and this now make the partner corpora invalid?

**Comment by TomazErjavec** [comment]
A lot has been done here, but I'm note sure if everything.
Still, this could be finalised for 4.1, so, attaching this milestone.

**Comment by TomazErjavec** [comment]
The parlamint2release.xsl has now the following template for idno fixing:
https://github.com/clarin-eric/ParlaMint/blob/18fc4a0d8792a626f5b2974e176516044cbad883/Scripts/parlamint2release.xsl#L249-L296

The resulting type and subtype values are as follows:
```
Distro$ cat ParlaMint-*.TEI/*.xml | grep '<idno ' | perl -pe 's/.+<idno //; s/>.+//' | sort | uniq
type="URI"
type="URI" subtype="facebook"
type="URI" subtype="government"
type="URI" subtype="handle"
type="URI" subtype="parliament"
type="URI" subtype="personal"
type="URI" subtype="twitter"
type="URI" subtype="wikimedia"
```

Is this ok for you @matyaskopp and we can close, or do we want to introduce more corrections?

**Comment by TomazErjavec** [comment]
Fixed as above, closing.
