### ISSUE TITLE
schemaSpecs: pb in head element

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#176]
I don't think that we need to have `<pb>` in `<head>`:
https://github.com/clarin-eric/ParlaMint/blob/4c61c8d78c76929aac85140efce080ca86e39754/Schema/ParlaMint-TEI.rnc#L294-L299

Or do I miss something?

**Comment by TomazErjavec** [comment]
No idea why it is here, and note too, actually. I simplified this (but left the old def as a comment, just in case) in 57050d2 and then merged dev into documentation, fixed the schemaSpecs there as well in b1ecbc4. Will fix again if it turns out some corpus doesn't validate now.

Btw., I think it is high time documentation were merged into main - can you do it?

**Comment by matyaskopp** [comment]
merged, closing
