### ISSUE TITLE
listPerson and nonspeaker persons

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#193]
Do we want to force listing persons that are members of parliament in `<listPerson>`?

It is possible to validate it because we know how many chairs are in parliament houses and the number should be equal to the number of persons with `role='MP'` that are affiliated with parliament (upper/lower house) at one time (except boundary date).

@TomazErjavec , what do you think? I am not sure if there is a corpus that passes these restrictions...

**Comment by matyaskopp** [comment]
Other nonspeaker persons that can be included are `minister` + `primeMinister`

**Comment by coltekin** [comment]
I think encouraging all PMs to be listed is a good idea. A warning  during validation would also be helpful for detecting missing PMs or speakers defined multiple times (e.g., due to different spelling of their name). However, I am not sure if we should add it as a strict validation rule. I can imagine cases where some PMs may be replaced mid-term (e.g., with a partial election or some sort of appointment after a number of PMs deceased or left the parliament for some reason), so resulting in more than the expected number of PMs. It may also be smaller than the expected number, if for example, some elected PMs do not become full members, i.e., something prevents them from joining the parliament formally after the elections.

**Comment by TomazErjavec** [comment]
I agree with @coltekin that it would be great if a warning were output and also that the validation should not fail because of missing MPs in the speaker list, not only for the reasons he gives, but also because this is more than was required in the project proposal.

The questiona might be moot in any case, as it is rather weird to have MPs that never said one single word. Still, I wouldn't be surprised if it does/did happen...

**Comment by matyaskopp** [comment]
> The questiona might be moot in any case, as it is rather weird to have MPs that never said one single word. Still, I wouldn't be surprised if it does/did happen...

Yes, it is weird to have silent MPs, but it happens, at least in Czech. You can see a difference between the number of speakers(476) and persons(485) in ParlaMint-CZ 2.1 - I have already included silent MPs in CZ data.

- it is really weird in small parliament, but I guess that in GB they have much more silent MPs
- another reason is that the MP is replacing someone at the end of term
- or corpus covers a time period that overlaps little with a term

**Comment by TomazErjavec** [comment]
This proposal doesn't seem likely to be ever implemented, also because, as noted, there are legit expections. So, closing.
If anybody disagrees, pls. reopen (I guess with Future milestone).
