### ISSUE TITLE
Setting up Makefile prerequisities 

### ISSUE THREAD

**Issue by sinikala** [clarin-eric/ParlaMint#221]
Is there some documentation on installing/configuring/troubleshooting Makefile requirements (notably saxon and jing)?

**Comment by matyaskopp** [comment]
Good question!
I will extend the [CONTRIBUTING in ParlaMint](https://github.com/clarin-eric/ParlaMint/blob/main/CONTRIBUTING.md) file with a description of the installation prerequisites and you can test it for me. 

I don't want to use target `make install-prereq` because it needs `sudo`.  And different systems can have different issues.

**Comment by sinikala** [comment]
Thank you @matyaskopp ! The addition was very helpfull. The instructions were pretty clear.
I had to do some extra operations (remove an old saxon symbolic link and add permissions) but otherwise went smoothly.
 `check-prereq` now passes and after a quick test at least` make val-schema-XX` seems to work.  

One thing that came to mind:
As Saxon and Jing are moved under `/opt` you might need to expand their permissions so that the Makefile script can access them (on Linux at least). I'm not sure whether this is clear to everyone who might be using these tools, so I wonder if adding that hint could be beneficial?

**Comment by matyaskopp** [comment]
> One thing that came to mind:
As Saxon and Jing are moved under /opt you might need to expand their permissions so that the Makefile script can access them (on Linux at least). I'm not sure whether this is clear to everyone who might be using these tools, so I wonder if adding that hint could be beneficial?

@sinikala thanks for testing.
I am not sure that I understand you correctly. I have `0644` for these `.jar` files and that is enough for java (all users can read it)


The only problem that I see is that this can all be done without `sudo` if we change all absolute paths that use these libraries
- https://github.com/clarin-eric/ParlaMint/search?q=saxon.jar&type=code
- https://github.com/clarin-eric/ParlaMint/search?q=jing.jar&type=code

and use some user folder...

But I am not sure if there are no other consequences. @TomazErjavec ?

**Comment by TomazErjavec** [comment]
> > One thing that came to mind:
> > As Saxon and Jing are moved under /opt you might need to expand their permissions so that the Makefile script can access them (on Linux at least). I'm not sure whether this is clear to everyone who might be using these tools, so I wonder if adding that hint could be beneficial?
> @sinikala thanks for testing. I am not sure that I understand you correctly. I have `0644` for these `.jar` files and that is enough for java (all users can read it)

I also think that this is not a problem, i.e. default permissions on /opt should assure world can read/execute. After all, that is what /opt is for, i.e. "the installation of add-on application software packages”.
 
> The only problem that I see is that this can all be done without `sudo` if we change all absolute paths that use these libraries
>     * https://github.com/clarin-eric/ParlaMint/search?q=saxon.jar&type=code
>     * https://github.com/clarin-eric/ParlaMint/search?q=jing.jar&type=code
> and use some user folder...
> But I am not sure if there are no other consequences. @TomazErjavec ?
Not sure what you mean by the URLs you gave, but, otherwise, indeed, it could be a very good idea to simply insist that the programs are installed in a gitignored folder inside the ParlaMint repo. The way it is now is simply that this is the way I have it on my machine, and so that is what I put in the Makefile in ParlaMint I.
So, my vote is, yes, let's move the programs to somewhere sensible inside Git. Not forgetting UD tools/.

**Comment by sinikala** [comment]
You are right, the issue was in my university's Linux distribution's stricter permission defaults (and I also misremembered the usual (Ubuntu) /opt defaults). Apologies for the confusion! The usual /opt defaults are indeed enough.
