### ISSUE TITLE
GR: interpretation of independent organization (εξωκοινοβουλευτικός)

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#246]
https://github.com/clarin-eric/ParlaMint/pull/239#issuecomment-1137198597 ... https://github.com/clarin-eric/ParlaMint/pull/239#issuecomment-1137217503 ... https://github.com/clarin-eric/ParlaMint/pull/239#issuecomment-1137237744 ... continue:
We have decided to use the `parliamentaryGroup` role for organizations representing political parties in parliament. 
We want to remove an `independent` role from all organizations.

In the SI corpus appear two organizations with `independent` role.
 - the first one is a group of independent persons - it is just a virtual group of persons where the persons do not act together. I believe that GR has the same type of organization: 
 https://github.com/clarin-eric/ParlaMint/blob/6b7fcd5ca234bfb56ab83679b697ace5c5e0148e/Data/ParlaMint-GR/ParlaMint-GR.xml#L410-L414
This organization should be removed because it is just saying that the members do not belong to any `parliamentaryGroup`
- the second SI organization is the regular `parliamentaryGroup`, but this organization uses the incorrect role `independent`. (should be fixed `independent`->`parliamentaryGroup`.)

But GR has an organization with an `independent` role that is not a `parliamentaryGroup` because its members are not members of parliament. 
https://github.com/clarin-eric/ParlaMint/blob/6b7fcd5ca234bfb56ab83679b697ace5c5e0148e/Data/ParlaMint-GR/ParlaMint-GR.xml#L415-L419

Should this organization also be removed?
Note that ministers are not related to the parliament. They are members of the government, which is a different organization (see chart in #227)

**Comment by DimitrisGk-iel** [comment]
Thanks for the feedback, we are going to have a group discussion about all this and let you know

**Comment by DimitrisGk-iel** [comment]
The first case is the one with the xml:id="party.ΑΝΕΞΑΡΤΗΤΟΙ_ΕΚΤΟΣ_ΚΟΜΜΑΤΟΣ" . 

When a person gets elected (s)he belongs to a political party. 
If during the parliamentary period this person leaves this political party (either because (s)he chooses to or because the political party expels him/her) then for the rest of the parliamentary period this person is a member of the Greek parliament but doesn’t belong to any party, (s)he acts as an individual. At the Greek parliament site these persons are grouped together and displayed under this name (ΑΝΕΞΑΡΤΗΤΟΙ_ΕΚΤΟΣ_ΚΟΜΜΑΤΟΣ). 
To our understanding we could either replace the role of the organization (role="independent" => role=”parliamentaryGroup”) or remove this organization completely and add a specific role to the affiliation of the corresponding persons. Are these persons the unaffiliated MPs in the graph of #227 ? Would the nonAttachedMember role (cf. the table in #245) be appropriate for such persons?

We believe that this is an issue that other countries might have encountered. So in order to have a unified approach we would like your opinion. How is this case encoded in other parliamentary corpora? Which approach do you think is the best?


The second case is the one with the xml:id="party.ΕΞΩΚΟΙΝΟΒΟΥΛΕΥΤΙΚΟΣ".

This case embraces all the persons that have been assigned a ministry but have not been elected to the Greek parliament. So these persons do not belong to a political party and are not members of the Greek parliament. In this case we could completely remove the organization and add as affiliation to the corresponding persons the government organization. What do you think about it?
Again in order to have a unified approach have other countries faced a similar case?

**Comment by matyaskopp** [comment]
> To our understanding we could either replace the role of the organization (role="independent" => role=”parliamentaryGroup”) or remove this organization completely and add a specific role to the affiliation of the corresponding persons. Are these persons the unaffiliated MPs in the graph of #227 ? Would the nonAttachedMember role (cf. the table in #245) be appropriate for such persons?

If I correctly understand the GR situation this ανεξαρτητοι (εκτος κομματος) organization is just a virtual organization. The members do not act together. **So it should be removed.** In CZ and SI we will not use this virtual organization. There is information that the person is a member of parliament in: https://github.com/clarin-eric/ParlaMint/blob/6b7fcd5ca234bfb56ab83679b697ace5c5e0148e/Data/ParlaMint-GR/ParlaMint-GR.xml#L476-L484 so the "ανεξαρτητοι (εκτος κομματος)" organization can be removed.

`nonAttachedMember` role uses only FR. I have to investigate what it means...


> This case embraces all the persons that have been assigned a ministry but have not been elected to the Greek parliament. So these persons do not belong to a political party and are not members of the Greek parliament. In this case, we could completely remove the organization and add as affiliation to the corresponding persons the government organization. What do you think about it?
Again in order to have a unified approach have other countries faced a similar case?

Great, this organization **should be also removed** and the members should be affiliated with the **government**.
And also remove all affiliations:
https://github.com/clarin-eric/ParlaMint/blob/6b7fcd5ca234bfb56ab83679b697ace5c5e0148e/Data/ParlaMint-GR/ParlaMint-GR.xml#L510-L517

note that the second affiliation is also wrong, the `deputyMinister` shouldn't be affiliated with **parliament**. 
If deputy ministers are members of the government, they should be affiliated with the government.

Ministers and deputy ministers are in a democracy usually affiliated with organizations with executive power - the government/ ministries.

**Comment by TomazErjavec** [comment]
I agree with @matyaskopp, so, to try to summarise:
* both of these virtual party organisations should be removed
* persons that have been affiliated with ΑΝΕΞΑΡΤΗΤΟΙ_ΕΚΤΟΣ_ΚΟΜΜΑΤΟΣ have this affiliation removed; they are members of the parliament and that they are indepdendent follows from the fact that they are not affiliated with and parliamentaryGroup
* persons that have been affiliated with ΕΞΩΚΟΙΝΟΒΟΥΛΕΥΤΙΚΟΣ also have this affiliation removed, and they should not be members of the parliament (i.e. they are not MPs), but should be members of the governemnt.

Does this make sense and is it ok with you?

**Comment by DimitrisGk-iel** [comment]
Yes we make the appropriate changes, and issue a new pull request

**Comment by matyaskopp** [comment]
I am closing this issue. It seems this has been fixed with https://github.com/clarin-eric/ParlaMint/pull/304
