### ISSUE TITLE
Marking unauthorized interjections by _regular_ speakers

### ISSUE THREAD

**Issue by hpreki** [clarin-eric/ParlaMint#267]
This is a extension of the discussion started in #79 on the encoding of unauthorized interjections.
 
In the AT data we have lots of _Zwischenrufe_ (my dictionary offers _break in_, _interjection_ and _heckling_ as translations) and we currently mark them as separate `<u ana="#unauthorized"`>. 
Like FR (@gclux) I would love to keep the encoding close to the current one.  In my opinion interjections are rich resources for studying both witticism and rudeness and deserve an exact and  explicit tagging. 

To recap the status in #79,  @matyaskopp suggested to use: 

> `<u ana="#intruder"...>` (or some other better word)

@gclux, @matyaskopp can we agree on a common `ana`-tag to be defined for that purpose? 

Giving it a second thought: in this case the usage of `ana` is in my opinion not exactly in sync with its current documentation:

> The <u> element should also have the ana attribute giving a pointer to the typology of types of speakers, which is especially important to enable the distinction between the speeches of a session chair (who mostly speak on procedural matters) from regular, and, possibly, guest speakers.

I.e. `ana` is to be used to classify the _speaker_ - while in _this_ context it actually is required to classify the _utterance-type_! 
99% of the interjections are from members of parliament - which I would classify as "regular" - only in very very few cases there might be a anonymous "shout-out" from members of the the public audience.  
But  maybe there  is some kind of mis-understanding, that @matyaskopp's proposal was intended to actually cover these (external) `#intruder` only? 

I of course can live perfectly well with a pragmatic solution like `<u ana="#regular #break_in>` , i.e. using `@ana` for classifying both the speaker and the utterance-type.

**Comment by matyaskopp** [comment]
@hpreki, my `intruder` suggestion did not gain acceptance. My idea was to use it for unauthorised speeches, but at the time I had made the suggestion I was not able to find the right word. I really like the `unauthorized` speech/speaker type.
There can be basically three types of speeches/speakers:
- `chair` - his speeches are technical - moderates meetings
- **authorised** - speeches that are allowed/introduced by the chairman "Mister XY can speech now: ..."
  - `regular` - we use it for MPs and members of government
  - `guest`
- **unauthorised** - speeches have been made without permission (eg undisciplined MP)

I have made this table: https://github.com/clarin-eric/ParlaMint/blob/data/Data/Metadata/ParlaMint-speaker-types-taxonomy.tsv
that lists all roles used in taxonomy (I have not checked if they are really in the data). I don't see the proper role for the unauthorised category (there are only `other` and `unknown`).

So my suggestion is to introduce a new `unauthorised` role. I think many roles can be removed(merged), but it would make sense to cover unauthorised speeches
@TomazErjavec, do you agree? (If Yes, please use British spelling)

**Comment by TomazErjavec** [comment]
Yes, I agree that we should have, in addition to the standard values of `#chair` etc. as the value of `u/@ana` also a new value that signifies - in technical terms - that the speech was, in the transcription, marked as a transcriber note. 

I don't like the name `unauthorised` though, because at least in the HR data, we have cases of such interruptions comming also from the chair of the session (e.g. reminding the speaker that (s)he is out of time), and, by defintion, what the chair says is authorised. So, I would suggest `interruption`, or maybe `interrupting`.  How does that sound @hpreki , @matyaskopp?

But be aware that these interruptions can - at least in theory - break a sentence of the speech proper. In [Parla-CLARIN](https://clarin-eric.github.io/parla-clarin/#sec-interruptions) we suggest that the speech proper is marked as interrupted with using `@prev` and `@next` as this would enable the linguistic analysis of the complete utterance (but with still some technical problems).

Anyway, if we agree on adding this new value, we would then need to also extend and at the same time fix the typology of speaker types. Here the [TSV](https://github.com/clarin-eric/ParlaMint/blob/data/Data/Metadata/ParlaMint-speaker-types-taxonomy.tsv) would be very useful. And I think we can stretch the meaning of this taxonomy to include a special type of speech not only types of speaker, or even better, say that this is a special type of speaker, i.e. the "interrupting speaker".

**Comment by matyaskopp** [comment]
> I don't like the name `unauthorised` though, because at least in the HR data, we have cases of such interruptions comming also from the chair of the session (e.g. reminding the speaker that (s)he is out of time), and, by defintion, what the chair says is authorised. So, I would suggest `interruption`, or maybe `interrupting`. How does that sound @hpreki , @matyaskopp?

I don't think that the interruptions made by the chairman are unauthorised. If someone is speaking too long or changes the topic the chairman is allowed to interrupt a speaker. So it is easier to implement it. We don't care if it is an interruption or not - we care if the speaker is allowed to speak or not.

**Comment by gclux** [comment]
In the latest version of the FR corpus, we have for the example in #79
<https://github.com/clarin-eric/ParlaMint/issues/79> this coding:
            <u xml:id="ParlaMint-FR_2017-07-25-E1020.u17" ana="#unknown">
               <seg>Très bien !</seg>
            </u>

I agree this should be improved, also because "unknown" should not be
related to "Government" (as it is now in the TSV). My proposal would be to
have a new attribute and to keep it for cases for which the speaker(s)
is/are "unidentified", whether it is an interruption or not.

When the chair interrupts someone, it is a different situation (since we
identify him). And, there may be another convention to track "interrupted"
speeches, as suggested in Para-CLARIN.

**Comment by TomazErjavec** [comment]
> I don't think that the interruptions made by the chairman are unauthorised. If someone is speaking too long or changes the topic the chairman is allowed to interrupt a speaker. 

OK, I agree with this of course.

> So it is easier to implement it. We don't care if it is an interruption or not - we care if the speaker is allowed to speak or not.

But here, if I understand you correctly, I disagree, because we do not know if speaker is allowed to speak or not. We just know that an interruption occured, which is signalled by a transcriber comment giving the text of the interruption, whether allowed (e.g. chair) or not (somebody else). The transcribers sometimes not who made the interruption, sometimes not, and even if they do, they have many and different ways of noting this. I don't think we can insist that the speaker is identified for every interruption (of course, if they are, it can be then marked with `u/@who`, otherwise not). So, I stand by the definition "in technical terms - that the speech was, in the transcription, marked as a transcriber note." 

But it seems @hpreki has most experience with this, so your opinion?

**Comment by TomazErjavec** [comment]
> I agree this should be improved, also because "unknown" should not be related to "Government" (as it is now in the TSV). My proposal would be to have a new attribute and to keep it for cases for which the speaker(s)  is/are "unidentified", whether it is an interruption or not.

Hm, I don't see anything wrong with having `u/@ana='#unknown', except that is it somewhat redundant, as you can infer that the speaker is unknown simply by the fact that we don't have `u/@who` for this utterance. But, yes, there is no reason to relate it to Govenment. I would really not introduce a new (or, rather, use another TEI) attribute, I don't see any need for that.

**Comment by gclux** [comment]
@TomazErjavec <https://github.com/TomazErjavec>,OK. "unknown",
"unidentified" or whatever, even just omitting ***@***.***

I just wanted to point out that this is different from "unauthorized" or
"interrupting"... which may be more difficult to recognize (not sure there
are transcriber notes, for the French corpus I would need to look into
different examples).

**Comment by hpreki** [comment]
| So it is easier to implement it. We don't care if it is an interruption or not - we care if the speaker is allowed to speak or not.

Not sure whether I understood @matyaskopp  correctly, but I beg to disagree: in my opinion the explicit identification as `#interruption`  is the thing I am really interested in. The study of interruptions could potentially be a whole field of research: what is the cross-party interruption rate?   Are there age and gender effects? (do young women get more often interruptions than older men?) 

The "interruption" topic should be disentangled from the "known/unknown"-topic (though at least in our data `ana="#unknown"` only occurs in interruptions etc., i.e. in utterances which originated in additional notes by the transcriber in contrast to the utterances by the appointed speaker) 
Even if it seems redundant: I would very much opt for an explicit `u/@ana="#unknown"` for unknown speakers! This also makes it clear, that the missing `u/@who` .

**Comment by TomazErjavec** [comment]
Thanks for the comments! I attempt to summarize:

- we have a new speaker role in the taxonomy, which I would then call "interrupting" in the sense of "the interrupting speaker". I would not use "interruptant" because this is not an English word :)

- if an utterance does not have the `@who` attribute, it must also be marked in `@ana` as `#unknown`, and vice-versa. @matyaskopp, this also means we need a check for this in the validation script and fix it in the v2tov3.

**Comment by hpreki** [comment]
From my point of view @TomazErjavec nice summary takes care of all my demands - and the issue can be closed (I suppose after `#interrupting` is added to the taxonomy and the Schema-documentation is updated)

**Comment by matyaskopp** [comment]
>Thanks for the comments! I attempt to summarize:
>- we have a new speaker role in the taxonomy, which I would then call "interrupting" in the sense of "the interrupting speaker". I would not use "interruptant" because this is not an English word :)
>- if an utterance does not have the `@who` attribute, it must also be marked in `@ana` as `#unknown`, and vice-versa. @matyaskopp, this also means we need a check for this in the validation script and fix it in the v2tov3.

Ok. To make sure that I understand it, I will try to summarize it with examples of what is possible (list of utterances witch do not make sense as a whole).

```XML
<!-- regular non-interrupting speeches speech -->
<u who="#person" ana="#chair">...</u>
<u ana="#unknown">...</u>
<!-- interruption samples -->
<u who="#person" ana="#chair #interrupting">...</u>
<u who="#person" ana="#regular #interrupting">...</u>
<u who="#person" ana="#guest #interrupting">...</u>
<u ana="#unknown #interrupting">...</u>
```

and it is also allowed to leave interruptions in transcriber notes:
```XML
<s>
  Tak my jsme dneska měli dvě možnosti -  ..... kolegy poslance Zahradila .....
  <vocal type="speaking"><desc>(Hlasy ze sálu: Zahradníka.)</desc></vocal>
  Zahradila?
</s>
```
I don't want to be pushed to annotate these situations. It can be difficult to do this in CZ data as there are no rules for transcriber notes. 

My feeling is that there are two dimensions that we are trying to fit into one taxonomy...
- `interrupting` and non-interrupting 
- speaker role characteristics: `chair`, `regular`+`guest`, `unknown`

**Comment by hpreki** [comment]
@matyaskopp I suppose that most countries will happily stay with the option to encode interruptions as transcriber notes. (that's actually exactly the way they are originally encoded in the AT-transcripts, btw.). 
The demand for having a `u/@ana="#interrupted"` is that FR/@gclux and AT went the extra mile to encode  interruptions as fully fledged `<u>`. And when doing so, it becomes very desire-able to have these  interrupting-`<u>` clearly marked as such - because syntactically they cannot be easily distinguished from "normal" `<u/>`

**Comment by hpreki** [comment]
> My feeling is that there are two dimensions that we are trying to fit into one taxonomy...
> * interrupting and non-interrupting
> * speaker role characteristics: chair, regular+guest, unknown

I initially also interpreted `@ana=(#regular|#chair|#guest)` to refer to a "taxonomy of speakers". 
While `@ana=#interrupted` was a "taxonomy of utterance-types".  
But when I reframe my interpretation of `@ana=(#regular|#chair|#guest)` as being more utterance-related than speaker-related it conceptually "feels" better, without having to change anything  :-)  
I.e. `<u @ana="chair">` does not add a type to the `speaker`, but still is typing the `<u>`. 

But then I still have a question about `@ana=(#regular|#chair|#guest)` : what does `regular` actually mean? Is it a synonym for "utterance my a member of parliament (other than the chair)"? What's about utterances by members of governments? Chancellors and ministers frequently give talks in the parliament but they are not MP. Are they "regular" or do we want/need an extra category for these?

**Comment by matyaskopp** [comment]
> I.e. <u @ana="chair"> does not add a type to the speaker, but still is typing the <u>.

exactly - every `@ana` is typing the element of which is an attribute. So here we are typing the utterances.

> what does `regular` actually mean?

It is a synonym for utterances by members of parliament+government other than the chair.

> do we want/need an extra category for these?

Yes, it would be nice, but sometimes eg in CZ data it is impossible to distinguish whether the person with two roles (minister + member of parliament) is speaking from the position of minister or a member of the government. So we (ParlaMint) have this one join role `regular`.

**Comment by TomazErjavec** [comment]
@matyaskopp, thanks for the examples, I've added now some of this to the [Guidelines](https://clarin-eric.github.io/ParlaMint/#sec-interruptions).  
So, apart from adding "interrupting" to the taxonomy, I think we are done.
Except for:

> Even if it seems redundant: I would very much opt for an explicit `u/@ana="#unknown"` for unknown speakers! This also makes it clear, that the missing `u/@who`.

I wanted to introduce this requirement into the Guidelines as well, but then started thinking it is not such a good idea, because we already have `#guest` who will be typically unknown as well, i.e. won't have `u/@who`. So, what then, `#guest #unknown` seems kind of silly to me, but, well, maybe you can convince me otherwise. Also, it seems to me that in any decent XML processing language, it is just as simple to say `not(@who)` as it is to determine that one of the IDREFs of `@ana` contains a reference to category that specifies somebody is unknown, no?

**Comment by hpreki** [comment]
> So, what then, #guest #unknown seems kind of silly to me, but, well, maybe you can convince me otherwise. 
 
 Our guests are typically _not_ unknown - e.g. the UN-secretary general Ban Ki-moon, and I expect an Ucrainian president to show up in several parliamentary protocols?

**Comment by matyaskopp** [comment]
> - if an utterance does not have the @who attribute, it must also be marked in @ana as #unknown, and vice-versa. @matyaskopp, this also means we need a check for this in the validation script and fix it in the v2tov3.

I am preserving this issue open because there is no issue for validation.
We did not allow `not(@who)` in ParlaMint v2, so I believe there is no need to handle it in v2tov3.

**Comment by TomazErjavec** [comment]
> Given the fact that we (AT) would be the only ones to use that kind of encoding, I am currently in favor of rather keeping things "as is" for ParlaMint - for the sake of simplicity and uniformity.

Yes, I agree!

> we can give the topic of including it in ParlaMint a second thought.

Actually, it would be better if we just leave it as it is for ParlaMint - the reasons above, but also so that we can have your additions MTed as soon as possible, rathen than waiting till end of August. The missing corpora might appear by then, and will meed to be MTed, which takes a while. And given that we should be finished by end of September, time will be at a premium!

So, with this, shall we close this issue?

**Comment by hpreki** [comment]
@TomazErjavec I agree, let's close this issue.
