### ISSUE TITLE
usage of time-element

### ISSUE THREAD

**Issue by hpreki** [clarin-eric/ParlaMint#290]
In the Schema documentation the usage for `<note type="time"/>` is prescribed as:
> **time**
> Date and time of the beginning and end of the debate
 
The  AT-protocols contain _lots_ of time-stamps other than the start- and end-time of sessions. 
My first reflex was to keep these additional time-stamps. 
* do you consider the usage of `<note type="time"/>` for preserving all kind of timing information a valid option?
 if _yes_: could you alter the documentation accordingly?
 if _no_:  do you have another proposal or should I just omit timing information? 
* When trying to (experimentally) use 
`<note type="time"><time when="16:02">16:02</time></note>` I noticed, that `time/@when` is tied to `att.datable.w3c`.  Is this choice a bug or a feature? Because this means  `time/when` expects an ISO-*date* I.e. my quick and easy `<time when="16:02">` is not valid, while `<time when="2022">`, which I consider non-intuitive for a `<time>`-element.

**Comment by matyaskopp** [comment]
in CZ, I am preserving timing information in this way:
https://github.com/clarin-eric/ParlaMint/blob/5eea8eae5f788aee485f8a7986ee1dbc493267f8/Data/ParlaMint-CZ/ParlaMint-CZ_2016-04-13-ps2013-044-02-001-157.xml#L201-L203

I have added a full datetime in every time note because I know the date of sitting. It is not documented because there are not many corpora covering this information.
We can at least extend the samples in <note> element to cover this situation: https://clarin-eric.github.io/ParlaMint/#TEI.note

**Comment by TomazErjavec** [comment]
I agree with both :) 

So, yes, the schema is already correct, I also think it is a good idea to have the full date-time info on `note[@type="time"]/time/@when` attribute: it is not difficult to add the date for the encoder, less so for the user. True, "2022" is then also valid according to the schema, but this I would consider wanton abuse, and we really can't deal with all sorts of such perversities (well, we could, e.g. with schematron rules, but this is surely overdoing it..). Anyway, this is simply copied from TEI, so, in order to be TEI-compiant, it must stay this way. So, yes, not a bug but a feature.

You are right, the documentation did not mention this use of the time element; I have now updated the documentation both of https://clarin-eric.github.io/ParlaMint/#sec-comments and https://clarin-eric.github.io/ParlaMint/#TEI.note and hope it is ok (the TEI of the ODD is in the documentation branch for now).

@hpreki , if you are happy with this, pls. close - otherwise, complain of course!
