### ISSUE TITLE
mentions of persons in utterances

### ISSUE THREAD

**Issue by hpreki** [clarin-eric/ParlaMint#294]
In our protocols mentions of  MPs  in utterances are reliably marked  in the original sources and the mentions also come with correct person-ids. 
I do not see a way to keep this information in the plain ParlaMint-TEI. Right now I would completely remove this existing information (e.g. `<u>I am asking <name type="person" who="#PAX123">John Doe</name> ...</u>`) when producing ParlaMint-TEI and then would _hope_ that a NER-module will later be able to correctly identify  these mentions as PERS-names again _or_ I will have  to come up with  ways to re-introduce  this information in  the post-NER-annotation-results (which is an effort I would like to avoid)

No big deal, I just wonder whether my perception is correct, that existing markup of person-names needs to be scraped for ParlaMint-TEI.

**Comment by matyaskopp** [comment]
Currently, ParlaMint doesn't support referencing a person from the name element. But I believe it will be in the future. 
If you want to add it, we can modify the schema (if @TomazErjavec agrees). 
But the encoding you suggested is not TEI-valid, I prefer to use `ref` attribute:
```XML
<u>I am asking <name type="PER" ref="#PAX123">John Doe</name> ...</u>
```

**Comment by TomazErjavec** [comment]
There are various aspects here:
* The text is actually not in `<u>` but in `<seg>`, so the suggestion is presumably to add `<name>` as valid content of plain-text version of `<seg>` 
* Technically this is a bit tricky, because now the definition of  `<name>` is in the schema of the ana (linguistically annotated) version, not in the plain text one, and is quite different (it expects tokens as content, as well as being quite complicated due to the CZ NER extensions) but I guess it could be done. Still, I am wondering if this would be of any use to @hpreki (or others), as they will need to produce a plain-text version of segments in order to feed them into the linguistic processing, so this info will be there lost anyway, and would case need to be re-introduced into ana. So, for these two reasons I am somewhat reluctant to allow `seg/name` in the plain text version. But if @hpreki insist, I can do it.
* Indeed, we do need an attribute for NE linking, and @matyaskopp suggests `@ref` which makes sense. But note that we already have `@ana` on names, which was introduced for CZ. So, @matyaskopp, should I change `name/@ana` to `name/@ref`? (I think this is a good idea, but fixings will need to cater for it).

**Comment by TomazErjavec** [comment]
> Preserving it in the text version can be tricky

I agree!

> I am suggesting only adding  `@ref` attribute.

OK, done in d12d6eb.

**Comment by matyaskopp** [comment]
adding `name/@ref` has been implemented, so closing this issue
