### ISSUE TITLE
documentation of affilition element

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#299]
affiliation element needs a review: https://clarin-eric.github.io/ParlaMint/#TEI.affiliation
- there is only one way to affiliate: `@ref`
- `@role` values need to be changed in example
- missing mention that if `@from` and `@to` is missing that the default whole corpus period is assumed

**Comment by TomazErjavec** [comment]
Thanks for noticing this, cf. below what I did. Note that it is in fact @katjameden that is in charge of the examples (with me to help of course, so both can be assigned such issues).

> there is only one way to affiliate: @ref

By this I presume you mean the note that says "Affiliation to organization can be done in three ways". True & I removed the note.

>   @role values need to be changed in example

Again, true, I now took the (suitably shortened) examples from the latest data-v2tov3-fixings, also inserted them in the [prose guidelines](https://clarin-eric.github.io/ParlaMint/#sec-affiliation).

>  missing mention that if @from and @to is missing that the default whole corpus period is assumed

This information is not specific to affiliation, but holds for any elements that can have the two atttributes. I added this explanation to the last bullet of the [Sec. on Standard values](https://clarin-eric.github.io/ParlaMint/#sec-standard).

All this in 535a2e0. 

@matyaskopp, pls. close of all ok now, otherwise complain!
