### ISSUE TITLE
speaker_types taxonomy

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#322]
Current `speaker_types` 
https://github.com/clarin-eric/ParlaMint/blob/5e4fdd6d638bd22bbf121ffcb605cd76ebf952b4/Data/ParlaMint-SI/ParlaMint-SI.ana.xml#L378-L403

needs to be extended with the following category:
- `interrupting`

as was summarized here: https://github.com/clarin-eric/ParlaMint/issues/267#issuecomment-1169843943
and exampled here: https://github.com/clarin-eric/ParlaMint/issues/267#issuecomment-1170103052

@TomazErjavec, did we agree on removing the `unknown` category and accepting the empty `@who` attribute?

**Comment by TomazErjavec** [comment]
Sorry, this issue escaped me. But now is a good time to address it.

As for adding "interrupting" speaker type: as far as I understand #267, the final agreement (although, to be fair, made without @matyaskopp) was that we don't introduce this category, because nobody in ParlaMint actually uses it, @hpreki included. Furthermore, we would then have a problem is somebody were an interrupting speaker, but at the same time the chair, i.e. the speaker role would need to become a multivalued attribute with all the problems this introduces. So, we do not introduce this category. Do we agree on this?

However, as noted in https://github.com/clarin-eric/ParlaMint/issues/722#issuecomment-1657210065, we also have 
"deputy_chair" in EE. I'd suggest we add this one into the taxonomy, it sounds sensible, even if nobody else uses is. @matyaskopp, do you agree?

**Comment by TomazErjavec** [comment]
> @TomazErjavec, did we agree on removing the unknown category and accepting the empty @who attribute?

Indeed we do @matyaskopp, release script now even removes them:
https://github.com/clarin-eric/ParlaMint/blob/a785b303aba5602d69e51542ded454a3fb2fa046/Scripts/parlamint2release.xsl#L380-L384

**Comment by TomazErjavec** [comment]
I think this has been sorted a long time ago, so closing. @matyaskopp, if you disagree, pls. reopen and write what would need to be done.
