### ISSUE TITLE
Multiple speakers for one utterance?

### ISSUE THREAD

**Issue by JessedeDoes** [clarin-eric/ParlaMint#33]
Sometimes there are multiple chairs in a meeting in our (BE) data, and the utterance is marked only as spoken by chair.
e.g.
```
 <u who="#Lalieux_Karine #Bracke_Siegfried" ana="#chair">
```

This validates with parla-clarin, but not with the parlamint schema.

TEI  (https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.ascribed.html) has for @who:
```Datatype | 1–∞ occurrences of teidata.pointer separated by whitespace``` 

Could it become:
```
who.att = attribute who { xsd:anyURIs }
```

in the schema?

**Comment by TomazErjavec** [comment]
I would avoid allowing multiple speakers on one utterance at all costs, as this will complicate processing all over the place. 

Also, what would this mean? That both are speaking at once and saying the same text seems unlikely. That one spoke, but was in the middle interrupted by another? But in that case, do you not have some indication of the interruption? Because then you could encode it as recommended in https://clarin-eric.github.io/parla-clarin/#sec-interruptions

Or maybe I misunderstand, because you also mention several chairs in a meeting, which is a different thing, and is not problematic even now, the role of chair is marked directly on an utterance, so it is unproblematic to have several chairs in a meeting.

Taking your example, if Karine is speaking, you write
```
 <u who="#Lalieux_Karine" ana="#chair">
```
but if Siegried is speaking you write
```
 <u who="#Bracke_Siegfried" ana="#chair">
```
and that is it.

But in case I misunderstand, pls. give a bit more explanation.

**Comment by JessedeDoes** [comment]
The point is that you just cannot tell. The files mark the speaker as "chair", and list two persons as co-chairs. So there is no way to decide who said what. 
```
                <u who="#Lalieux_Karine #Bracke_Siegfried" ana="#chair">
                    <note xml:lang="nl">De voorzitter:</note>
                    <seg xml:id="ParlaMint-BE-FP-54-commissie-ic003.seg.3" xml:lang="nl">Collega’s, om het debat te kunnen behappen, is er het voorstel van mevrouw Lalieux dat per fractie één persoon als woordvoerder of woordvoerster optreedt, en dat wij die uiteenzettingen zouden beperken tot tien minuten, zonder evenwel de toegemeten tijd te zullen afwegen op een apothekersweegschaal. Daarna volgen de replieken van de staatssecretaris en de minister. Daarna is er een vrije tijdsruimte waarin elkeen het woord kan nemen. Daarna zien wij wel.</seg>
                    <seg xml:id="ParlaMint-BE-FP-54-commissie-ic003.seg.4" xml:lang="nl">Als wij van bij het begin het debat kunnen structureren door iedereen tien minuten spreektijd per fractie te geven, dan kunnen wij het debat vooruithelpen en behappen.</seg>
                </u>

```

De vergadering wordt geopend om 15.06 uur en **voorgezeten door mevrouw Karine Lalieux en de heer Siegfried Bracke**.

La séance est ouverte à 15.06 heures et **présidée par Mme Karine Lalieux et M. Siegfried Bracke.**


......


**De voorzitter**: Collega’s, om het debat te kunnen behappen, is er het voorstel van mevrouw Lalieux dat per fractie één persoon als woordvoerder of woordvoerster optreedt, en dat wij die uiteenzettingen zouden beperken tot tien minuten, zonder evenwel de toegemeten tijd te zullen afwegen op een apothekersweegschaal. Daarna volgen de replieken van de staatssecretaris en de minister. Daarna is er een vrije tijdsruimte waarin elkeen het woord kan nemen. Daarna zien wij wel.

**Comment by TomazErjavec** [comment]
Thanks, now I understand. Drat!

Nevertheless, I would still not change the schema, for 3 reasons:
- As mentioned, this complicates processing, instead of just looking up the pointer, you always have to tokenise the value first and then do look-up. But this is not such a problem, a bigger one is that the analyses become much more opague, as you can't count on 1-1 betwee speech and speakers.
- Another problem is that, to my mind, the cases where you have IDREFS have an implicit conjunction between their values. E.g. we use `<meeting ana="#parla.sitting #parla.lower" n="ps2013/016/01">ps2013/016/01</meeting>` meaning that this meeting represents a sitting and that it is a meeting of the lower house, a "lower house sitting" for short. And not that it represents a sitting or a meeting of the lower house. Also seeing your `<u>` with two speakers, my intuition was immediatelly that you want to incdicate that they are both speaking. But now I see that they are meant to be disjunctive, so, opposite from all the other uses of IDREFS we have.
- Finally, statistics: from the 8 corpora that I had dealings with so far, you are the only one reporting this issue, and I hope that even in your case it is infrequent (fingers crossed).

So, with this, I would say IDREFS is out. But I still don't know how to solve the problem. Randomly take just one? Have a vitual collection of people? Hm...

On the up-side, the reason we introduced "chair" into utterances was that for almost all analyses you want to get rid of the utterances of the chairs, as they talk only about procedural matters, but talk often. So, if you include them, they will completely skew any analyises, e.g. which political party talked the most - it will be the one that had the chair, which is uninteresting.

**Comment by matyaskopp** [comment]
I think you can just remove the attribute `who` and keep only `@ana="#chair"`... It is the cleaner way than randomly taking one person...

And probably you can add different affiliations with parliament organization.

**Comment by JessedeDoes** [comment]
We could make make this contingent on the solution we choose for the `empty who vs link to Anonymous` issue.

- If we accept empty who, we can do that here as well
- If we don't, we link either to Anonymous or to some virtual person representing a small group of people
-

**Comment by TomazErjavec** [comment]
> If we accept empty @who, we can do that here as well

Great, and, yes, accepted as per #29.
