### ISSUE TITLE
schema: Multi-token words

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#37]
As wrongly reported here: #36
It would be nice to allow `@xml:id` in all `w` elements.

Furthermore, it is a must to allow `@join` attribute in all `w` elements. Consider this sentence from our corpus:

> Ještě bych pochopil, **kdyby**, jak to včera říkal pan ministr průmyslu, obchodu, dopravy a nevím ještě čeho, ale určitě ne podnikatelů a podnikání, že v tom doplňkovém prodeji ty velké obchody mají nárůst tržeb jenom o 5 %.

The word **kdyby** consists of two tokens and can be represented (I have temporarily remove `@xml:id` to "pass" validation):
```
                       <w join="right">kdyby<w xml:id="ParlaMint-CZ_2020-11-19_ps2017-070-01-001-001.u65.p7.s3.w6"
                             lemma="když"
                             msd="UposTag=SCONJ"
                             ana="pdt:J,-------------"
                             norm="když"/>
                          <w xml:id="ParlaMint-CZ_2020-11-19_ps2017-070-01-001-001.u65.p7.s3.w7"
                             lemma="být"
                             msd="UposTag=AUX|Mood=Cnd|Person=3|VerbForm=Fin"
                             ana="pdt:Vc-------------"
                             norm="by"/>
                       </w>
```

**Comment by TomazErjavec** [comment]
In my corpora we didn't need IDs on such w[w] words, but your are of course right that one can need them - even more so for `@join`, so I am adding these attributes. Btw. `@join` is also allowed on w/w, so, on the inner words, which I'm not sure makes much sense, but the schema gets (even more) messy otherwise. 

Additionally, I added (optional) linguistic attributes on such w[w] words, as I can see cases where you analyse them directly (and not only analyse the constituent words). 

Pls. test using schema of next commit.

One more thing: right now only w/w is allowed. Can you think of cases where it might make sense to allow combinations with punctuation, like w/pc, or pc/pc (so, 1 word normalises into a combination of words and punctuation, or a punctuation is normalised into several punctuations)? I would say no, but I am not sure.

**Comment by matyaskopp** [comment]
https://github.com/clarin-eric/ParlaMint/commit/d9f6a83b2bcc577ce30e2917b45263444049dd00 solves my issue with `id` and `join`.

> One more thing: right now only w/w is allowed. Can you think of cases where it might make sense to allow combinations with punctuation, like w/pc, or pc/pc (so, 1 word normalises into a combination of words and punctuation, or a punctuation is normalised into several punctuations)? I would say no, but I am not sure.

Keeping opened, not answered everything. I have to think about that or ask someone more experienced.

**Comment by matyaskopp** [comment]
I don't think either. I think we can close this issue until someone comes with some example...

**Comment by TomazErjavec** [comment]
OK, closing.
