### ISSUE TITLE
Problems with party affiliation

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#38]
# political party vs. political group

I have an example of Václav Klaus (the son of our former president), only relevant affiliations included:
```
          <person xml:id="VaclavKlaus6498">
            <persName>
              <surname>Klaus</surname>
              <forename>Václav</forename>
            </persName>
            <idno type="URI">https://www.psp.cz/sqw/detail.sqw?id=6498</idno>
            <sex value="M">mužské</sex>
            <affiliation ref="#parliament.PSP8" role="MP" from="2017-10-21"/>
            <affiliation ref="#politicalParty.ODS.155" role="candidateMP" from="2017-10-21"/>
            <affiliation ref="#politicalGroup.ODS.1295" role="member" from="2017-10-24T00:00:00" to="2019-03-17T00:00:00"/>
            <affiliation ref="#politicalGroup.Nezaraz.1500" role="member" from="2019-03-17T00:00:00"/>
          </person>
```
**Related parties and political groups:**
He was elected as a candidate of political party ODS
```
          <org xml:id="politicalParty.ODS.155" role="politicalParty">
            <orgName full="yes" xml:lang="cs">Občanská demokratická strana</orgName>
            <orgName full="yes" xml:lang="en">Civic Democratic Party</orgName>
            <orgName full="init">ODS</orgName>
            <event from="1900-01-01"><label xml:lang="en">existence</label></event>
          </org>
```
He joined to political group ODS in parliament
```
          <org xml:id="politicalGroup.ODS.1295" role="politicalGroup">
            <orgName full="yes" xml:lang="cs">Poslanecký klub Občanské demokratické strany</orgName>
            <orgName full="yes" xml:lang="en">Political group Civic Democratic Party</orgName>
            <orgName full="init">ODS</orgName>
            <event from="2017-10-24"><label xml:lang="en">existence</label></event>
          </org>
```
then he joined an independent MP group
```
          <org xml:id="politicalGroup.Nezaraz.1500" role="politicalGroup">
            <orgName full="yes" xml:lang="cs">Nezařazení</orgName>
            <orgName full="init">Nezařaz</orgName>
            <event from="2019-03-15"><label xml:lang="en">existence</label></event>
          </org>
```
Then he created a new political party "Trikolóra hnutí občanů" (2019-06-25), but there is no data of this event in the source data...

So the question is: What organization is relevant?
a **political party** or **political group** ( https://public.psp.cz/en/sqw/hp.sqw?k=193 )...

_Originally posted by @matyaskopp in https://github.com/clarin-eric/ParlaMint/issues/31#issuecomment-771843409_

**Comment by TomazErjavec** [comment]
An added problem here is that all the other corpora (so, except CZ), simply have person affilliated with political parties as members of these parties e.g.
https://github.com/clarin-eric/ParlaMint/blob/d9f6a83b2bcc577ce30e2917b45263444049dd00/ParlaMint-SI/ParlaMint-SI.xml#L530

This might reflect a different way of gathering infomration (i.e. the compilers of the corpus did in fact check party membership of the persons), or it might be the result of simplistic viewing of the relation of people and parties (so, the fact that somebody was in a politicalGroup which is named the same as a politicalParty, they were taken to be a member of the politicalParty. 

So, we keep this open in the hope that we will figure out what is happening at some point and come up with a consistent way of annotating this.

**Comment by TomazErjavec** [comment]
We now have several more corpora, where the problem of the affiliation of a speaker with a politicalParty or a politicalGroup is relevant:
- IT had politicalGroup, but, at my urging (in order to keep things simple) changed it to politicalParty, although they were not too happy with this
- FR has politicalGroup, and are rather disinclined to change it to politicalParty

In the TEI it doesn't really matter if a corpus has politicalParty or politicalGroup or both. The problem comes when converting the TEI to the vertical format, and hence what shows up in the concordancer. Currently we have there the following relevant attributes on speech:
```
<speech ... speaker_party="PS" speaker_party_name="Parti Socialiste">
```
For the CZ case (which has both politicalParty and politicalGroup), I just put the politicalGroup into the vertical speaker_party (and speaker_party_name). I can contiue to do the same with the new languages, or admit that these are two different things, and encode each one separately, for example (sorry for the silly example):
```
<speech ... speaker_party="PS" speaker_party_name="Parti Socialiste" speaker_group="PSML" speaker_party_name="Parti Socialiste et Machine Learning">
```
which would solve the problem as far as the concordancer goes, except that the corpora would become somewhat less comparable, but it could be argued that this is better than faking it. So, with this solution most corpora would always have empty 2 of the 4 attributes, but some (currently only CZ) would have both.

I am in two minds if it makes sense to extend the concordancers attributes, given that we have already quite a few, and the CZ seems to be the only case where they use both. Currently I am leaning towards leaving everything as it is, but if anybody thinks differently, now is the time to speak up!

**Comment by matyaskopp** [comment]
For CZ, you can keep only `politicalGroup`. Affiliation of a person with `politicalParty` has only `candidateMP` role and it does not mean that the person is a regular member of this party - it only means that he has been mentioned in party-list  (explained here: https://github.com/clarin-eric/ParlaMint/issues/31#issuecomment-771843409)

**Comment by atomm** [comment]
For IT as well the only formal belonging of an MP is to a politicalGroup (Parliamentary Group in the words used within the Italian parliament) which is the only organization formally recognized within the parliament. That said we are ok with both solutions since, in most cases (for bigger parties) there is a 1:1 correspondence between a party and a group. Smaller parties instead need to join forces to constitute a group (N:1) since a rule dictates that in order to form a group you need at least 20 deputies (in the Chamber) or 10 senators (in the Senate). (The Chamber's size is double).

**Comment by TomazErjavec** [comment]
> For IT as well the only formal belonging of an MP is to a politicalGroup

If it is not too much bother, then you could change all your politicalParty to politicalGroup, so it better reflects reality.
In the concordancer we now have that politicalGroup is displayed in preference to politicalParty (where both exists for a person), if only one is there, then that one is displayed.

**Comment by atomm** [comment]
sure, no problem.

**Comment by TomazErjavec** [comment]
It turns out that IT would (in the vertical files) also like to have people that have other affiliation roles, not just member (and candidateMP for CZ) to be taken as members of their politicalGroup (or also politicalParty).

This seems reasonable to me, so I will be adding these roles to qualify for politicalParty or politicalGroup membership: 
- member
- president
- vicePresident
- secretary

I hope this is not problematic for others, if yes, pls. complain!

**Comment by matyaskopp** [comment]
`politicalGroup` represents `politicalParty` in parliament, so it would be nice to bind these two organizations with `//listOrg/listRelation/relation` in the next ParlaMint release. 

Something like:
```
<relation name="represent" 
          active="#politicalGroup.CSSD.1107" 
          passive="#politicalParty.CSSD.153" 
          from="2013-10-29" 
          to="2017-10-26"/>
```

**Comment by TomazErjavec** [comment]
> it would be nice to bind these two organizations with //listOrg/listRelation/relation in the next ParlaMint release.

Indeed yes - but not that you are the only one that has both politicalParty and politicalGroup...

**Comment by TomazErjavec** [comment]
@matyaskopp, is there anything more to be said here?

**Comment by matyaskopp** [comment]
> @matyaskopp, is there anything more to be said here?


@TomazErjavec no, I am closing it
