### ISSUE TITLE
Short segments in other language

### ISSUE THREAD

**Issue by lnnoemi** [clarin-eric/ParlaMint#400]
The Hungarian corpus contains cca 210 segments written in other languages. 
I encoded this into langUsage, but the proportion number (0.002 for Polish, for example) does not pass the validation.
Should I omit the usage attribute here?

**Comment by TomazErjavec** [comment]
> The Hungarian corpus contains cca 210 segments written in other languages. I encoded this into langUsage, but the proportion number (0.002 for Polish, for example) does not pass the validation.

Yes, for some reason, the TEI Guidelines [specify this](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-language.html#tei_att.usage) is a nonNegativeInteger, and then, so do we. Arguably a bug. 

A tricky question - I have no silver bullet, but 

> Should I omit the usage attribute here?
Hm, this would give the impression that there is a substantial amount of such segments. One option would be to say this is 1 (percent), as the Guidelines do say "specifies the approximate percentage".

Another would be to just use the language code "und" for unetermined, but I guess you do in fact determine the language in the utterances? Given how few there are, I would just set them as "und".

The question is then also how you then linguistically analyse such segments. Just "X" and "Foreign="yes"" for all the words?

**Comment by lnnoemi** [comment]
Yes, I have the language code for these segments. (Some of them are `mul`, the same sentence in the two languages.)
If I set all of them to 1% (10 languages), we get 90% for Hungarian, which is far less than the truth: 99.97%.

I found these segments during the linguistic analysis, so I have no solution for their analysis yet...

**Comment by matyaskopp** [comment]
Are there translations of these segments into Hungarian in proceedings?
If so, I am suggesting changing these foreign parts into `<note>`, we can add a new `type` for that - I didn't think about it in depth, but this hack can save a lot of work.

**Comment by lnnoemi** [comment]
I can check, but I guess there.
So this `<note>` thing sounds ok, and it solves the problem of the linguistic analysis as well.
What will be the `type` for that?

**Comment by TomazErjavec** [comment]
> Yes, I have the language code for these segments. (Some of them are `mul`, the same sentence in the two languages.) If I set all of them to 1% (10 languages), we get 90% for Hungarian, which is far less than the truth: 99.97%.

Very true - a solution might be to give them "0", which is much closer to the truth than 1. In fact, that sounds to me like the perfect solution, for a given value of perfect... But see below.

> I found these segments during the linguistic analysis, so I have no solution for their analysis yet...

Yes, this one is tricky. Also because if the segment is marked as being in some (non-hu) language, and you give all of them morphology as Foreign, then, this would actually mean they are foreign words for the language marked on the segment, which if course is not the case. And it is also not clear how to do the syntactic analysis of such segments.

As for using `<note>` I am less than enthusiastic, because we use notes only for transcriber comments, but the foreign language segments are not such comments.

We have so far used `seg/@xml:lang` only for cases where the corpus is truly bi-lingual (e.g. BE), and then all the segments marked with a language are linguistically analysed using the model for that language. I would like to keep it that way, and your case is of course different. I see two options:

1. Do *not* mark the segments for language, and just analyse them with the hu model. You will probably get junk annotations, but as there is so little of this content, they should not cause too many problems. If you are feeling very keen, you could post-hoc change all their UPoS to "X" and morph. features to "Foreign=Yes". Syntactic parses will remain junk, but hopefully CoNLL-U validations won't complain.

2. You can continue to mark these segments for language, but their only content would be [gap](https://clarin-eric.github.io/ParlaMint/#TEI.gap). We would introduce a new value fo its type attribute (e.g. "foreign"), and you could put the original text into gap/desc. This is very similar to note, except we don't abuse the semantics of note.

All in all, I incline towards the second option. If you agree, I will add the new `gap/@type` value into the schema + ODD.

**Comment by lnnoemi** [comment]
OK, `gap` sounds better than `note`.
And then the `langUsage` would be set to 0 for all these languages, and 100 for Hungarian.

**Comment by TomazErjavec** [comment]
OK. Added `gap/@type=foreign` to schema (currently in the documentation branch) and [explanation](https://clarin-eric.github.io/ParlaMint/#sec-gaps) in the Gudelines.
Pls. close if you are happy with the explanation and can validate sucessfully.

**Comment by lnnoemi** [comment]
Sorry for reopening: should I already see the changes during schema validation? I think I updated my fork, but the validation says `"reason" is invalid; must be equal to "editorial" or "inaudible"`.

**Comment by TomazErjavec** [comment]
This looks like you still don't have my change. It is in the documentation branch. Maybe wait for @matyaskopp to merge into data or main, and try to synch and valdate. If still doesn't work then pls. send or point me to the offending file, and I will test as well. Sorry for the problems!
