### ISSUE TITLE
Person changing name over time

### ISSUE THREAD

**Issue by hpreki** [clarin-eric/ParlaMint#439]
Persons may have their names changed - typical case is due to marriage.
In our original metadata-sources we do have  some information on when these changes happened. 
I naively added the info as `@from` and `@to`  in `persName`  but this is obviously not allowed by the Schema. 

```xml
   <persName to="2005-06-01"><surname>Glawischnig</surname>.../persName>
   <persName from="2005-06-01"><surname>Glawischnig-Piesczek</surname>...</persName>
``` 
Can I correctly assume that for now  the preferred solution is to simply _drop_ the timing-information completely?

**Comment by matyaskopp** [comment]
Currently, we don't have this information because (I guess) sources of metadata just contain current information and don't store the previous states (CZ case).
But in the ParlaMint-UA corpus, I guess I will have to solve this. @annaParla will surely welcome this improvement.

I am not sure about the consequences for scripts that create derived formats and load data to noSketch...
I can imagine that only the newest name will be used in these tools, but @TomazErjavec has to say if we want this.

**Comment by hpreki** [comment]
Iff we keep the multiple-name-info (and I thought we should) which is easy by having multiple entries for `<persName>` we still have to decide  _if and how_ to encode _timing_ information. 
Without a quick solution in sight I just would for the moment _keep_ multiple    `<persName>`  but would remove  the `@from` and `@to` to ensure validation.

**Comment by TomazErjavec** [comment]
I know about this problem since it was mentioned by our colleague from Ukraine. It does add some complication but not horribly much, so I would implement it. It means a change in the schema and some added complication for [format-name](https://github.com/clarin-eric/ParlaMint/blob/47a6a842d5a6447266f3ce0d95ad83bdac66673e/Scripts/parlamint-lib.xsl#L223).

> Iff we keep the multiple-name-info (and I thought we should) which is easy by having multiple entries for <persName> we still have to decide if and how to encode timing information.

What is wrong with the solution you already suggested, just with the change that the dates should not overlap, e.g.
```
<persName to="2005-06-01"><surname>Glawischnig</surname>.../persName>
<persName from="2005-06-02"><surname>Glawischnig-Piesczek</surname>...</persName>
```
The validation (XSLT, can't do that in RelaxNG) would have to check that if there is more than one persName, they should have the to and/or from attributes and they should not overlap, and should not have gaps. Or maybe not check this (because it is complicated), and hope that everybody gets it ok. And I could functionally check this in format-name (exactly 1 persName must be chosen for a given date).

> Without a quick solution in sight I just would for the moment keep multiple <persName> but would remove the @from and @to to ensure validation. Is that o.k. for you?

Um, no, as that would mean a person's name would be some horrible concatenation of both variants, or a more or less random choice of one of them.

So, everybody here in favour of the extension?

**Comment by matyaskopp** [comment]
Agree.

For now, we can skip the validation. In future [`Scripts/validate-parlamint-particDesc.xsl`](https://github.com/clarin-eric/ParlaMint/blob/main/Scripts/validate-parlamint-particDesc.xsl) can be extended.

**Comment by TomazErjavec** [comment]
Did this now as far as the schema and [Guidelines](https://clarin-eric.github.io/ParlaMint/#sec-speakers) go (documentation branch). Let me know if you spot any problems.
Next comes the modification of the scripts, which will be done in the devel branch.

**Comment by TomazErjavec** [comment]
Modified the scripts now as well. Note that hasn't been extensivelly tested, so don't be surprised if it break - @hpreki, I am counting on your data to tell us if it is all ok (the results show up in vertical and metadata tsv files).

**Comment by TomazErjavec** [comment]
I think this has now been sorted, so, closing.
