### ISSUE TITLE
Named entities and element <name>

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#46]
This issue is closely related to #41 

Thinking about our [elaborate taxonomy](https://ufal.mff.cuni.cz/~strakova/cnec2.0/ne-type-hierarchy.pdf) again.

TEI element `<name>` is primarily intended for proper nouns: https://tei-c.org/release/doc/tei-p5-doc/en/html//CO.html#CONARS
But Named entities' tasks can take care of a wider area of words:
- time expressions
- numbers
- or some artifact names

So I am suggesting using the different element and element `name` use only for proper nouns. 

Possibilities:
- Everything that is not a proper noun put to `<rs>`. https://tei-c.org/release/doc/tei-p5-doc/en/html//ref-rs.html
   - It is a simplification but probably the easiest way
- Use some meaningless element `<ab>`
- Use various elements - I am not sure about that. It would really complicate a situation.

**Comment by TomazErjavec** [comment]
I agree, `<name>` is for proper names, not time expressions or numbers, so it would indeed make sense to separate the two., i.e. use some other element for those that can't be reduced to PER/ORG/LOC/MISC. It is less clear what it could be:
- `<rs>` doesn't seem exactly ok, as that means a "referencing string", and a date doesn't really reference anything (except "the actualy date", but then "dog" also references an actual dog...). 
- `<ab>` is not ok, as it can't be contained by `<seg>`, and our text is inside segments.
- `<seg>` would be the obvious choice, as it belongs to the right level, but we already use it for somewhat paragraph like elements, and I think it would be confusing to also use it for NER.
- various elements is very tempting, yes, it would somewhat complicate the situation, but you would annotated exactly what you mean. Do you need anything apart from date, time, nun?

So, all in all, I am leaning towards the last option, with `<rs>` in second place (slightly abusing its semantics). 
Another way would be to leave `<name>` the way it was before (no nesting, no `@ana`), but allow it to contain `<rs>` which would then model your NER types (and `<rs>` could also be on the same level as `<name>`, i.e. in a `<s>`) - so you would get your own element, but we would keep the good ol' `<name>`. And here my head starts to hurt...

@matyaskopp ?

**Comment by matyaskopp** [comment]
As suggested in a private google sheet, new named entities related elements are:
`date`, `time`, `email`, `ref`, `num`, `unit`

so if you can please add them to the schema. All elements should have an attribute `ana`.

I will update our data and test the schema.

**Comment by TomazErjavec** [comment]
>  if you can please add them to the schema
Added them, but it is relatively large change and did no testing, so they are in the NER branch for now.

Pls. report if validation (preferably on the whole corpus) is ok - e.g. I wasn't sure about the nesting, but it seems only `<name>` can nest, and I really hope this is the case, as otherwise there are problems with TEI compatibility.

**Comment by bansp** [comment]
Isn't `<rs>` meant to be a generic container for strings referring to named entities (and I wouldn't pay too much attention to the deep semantic analysis of name of the element, because it's exactly meant to be generic, and then the `@type` attribute serves to cut it down to usable fragments). 

If you were to use `<rs>` for NEs, I would consider dropping `<name>` altogether, because proper names cut across the typology of named entities (OR e.g. use it inside `<rs>` only if the rs is also a proper name, in this way catching both birds).
All in all, I wouldn't advise being tied too much to the existing repertoire of TEI elements, because it's a bit of a chaos that is meant to be tamed in a particular customization. I'd just start by sketching the goal, and adjust the elements (and types) to that goal.

Incidentally, note that the existing TEI *Name set of elements attempts some rough typology (orgName, persName, etc.), but again, I'd use that only if the TEI repertoire matched the intended goals, otherwise just `<rs>` with a more or less precise taxonomy (and if you encode the taxonomy as `<taxonomy>`, then use `<rs>` with `@ana` instead of `@type`). It might be argued that this very solution is semantically saner, because `@type` might be seen as classifying the `<rs>` from the linguistic point of view, while `@ana` resolves the semantics.

**Comment by TomazErjavec** [comment]
> Isn't `<rs>` meant to be a generic container for strings referring to named entities

Indeed yes, but what @matyaskopp wants to annotate is also date and time, measure units, etc. And while these are typically considered named entitites in NER tasks, they don't really correspond to named entities (at least as far as I understand) in the TEI sense. What does "31043" or "kg" refer to? OK, you could say to whatever it is you are counting or measuring, but it seems somehow weird, at least to me. Or am I wrong?

There is also the problem that in ParlaMint we already have name, and all the others will have only that, except CZ, which want more. But, if numbers etc are fair game for rs, maybe I/we should think again..

And, yes, I agree with `@ana` being better than `@type`, as everywhere else we do have `@ana`, and we even have a taxonomy for NER, cf. eg. 
https://github.com/clarin-eric/ParlaMint/blob/56309414547b74e792f14ba2282ca8e85360ccf1/ParlaMint-SI/ParlaMint-SI.ana.xml#L267-L285. 

By using `name/@type` I was trying to be too faithful to the Guidelines here I think.

So, @bansp, @matyaskopp , do you think `<rs>` with `@ana` would be better than the whole gamut of name/date/time/num/ref.. and the first having `@type`? I know it's a bit late in the game, but, still...

**Comment by matyaskopp** [comment]
> So, @bansp, @matyaskopp , do you think <rs> with @ana would be better than the whole gamut of name/date/time/num/ref.. and the first having @type? I know it's a bit late in the game, but, still... 

**`<rs>`**:

- simple, we have merged all proper names `<*Name>` to element `<name>`. So using `<rs>` for the rest of named entities make some sense

**varied elements**:

- possible future annotations, dates can be annotated/dated in attributes: `<date type="occasion" when="--01-01">New Year's Day</date>`
- all element can be nested so it is not a problem to represent: `<date ana="ne:tf"><w>Zmrtvýchvstání</w> <name ana="ne:pp"><w>Páně</w></name></date>` (Easter Sunday)

I am not certain what is better...

**Comment by matyaskopp** [comment]
To give everything a second thought I vote for **varied elements** (date, time, email, ref, num, unit). I don't want to change `rs` to `date` i case I decide in the future to do some additional annotations:
- `date` and `time`: `@when`, `@type`
- `num` + `unit` -> wrap with `measure` (`<measure><num>2</num> <unit>kg</unit></measure>`)
I think that we should add annotations in the future, not change the schema.

**Comment by TomazErjavec** [comment]
> To give everything a second thought I vote for varied elements (date, time, email, ref, num, unit).

OK, so be it, this is now implemented - hopefully correctly - in 99071c3.
