### ISSUE TITLE
"ParlaMint-IS-taxonomy-parla.subcorpus.xml" instead of "ParlaMint-taxonomy-subcorpus.xml"

### ISSUE THREAD

**Issue by starkadur** [clarin-eric/ParlaMint#477]
I factorized ParlaMint-Is while a go and all seemed to go well. But when looking at the taxonomies I notice that I have the included file "ParlaMint-IS-taxonomy-parla.subcorpus.xml".
Should it not be "ParlaMint-taxonomy-subcorpus.xml" ?

Was it made corpus specific (and thus distinguished by including the country code IS) because of the "parla" in taxonomy-parla.subcorpus? I think I did not receive no error because of this.

**Comment by matyaskopp** [comment]
It happened because you did not have a `taxonomy[@xml:id="subcorpus"]` but you have used `taxonomy[@xml:id="parla.subcorpus"]`. 
The factorization script check if it knows the taxonomy:
- if yes then it is common and it is called `ParlaMint-taxonomy-{taxonomy-id}.xml` (or  `ParlaMint-taxonomy-{taxonomy-id}.ana.xml` for taxonomies specific for annotated version)
- if no then it is corpus-specific taxonomy (like your `parla.subcorpus`) and it is called `ParlaMint-XX-taxonomy-{taxonomy-id}.xml` (or  `ParlaMint-XX-taxonomy-{taxonomy-id}.ana.xml`)

known common taxonomies:
https://github.com/clarin-eric/ParlaMint/blob/c5fd7aaee29b18cf537a84850d41c4930250de51/Scripts/parlamint-factorize-teiHeader.xsl#L32-L39

**Comment by TomazErjavec** [comment]
I think this has all been fixed, so, closing.
