### ISSUE TITLE
CoNLL-U to ParlaMint

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#5]
A free contanuation of email discussion [subj. UD & UPOS tags].

I have this script [udpipe2.pl](https://github.com/ufal/ParCzech/blob/master/src/udpipe2/udpipe2.pl) (related perl package is here: [ParCzech::PipeLine::FileManager](https://github.com/ufal/ParCzech/blob/master/src/lib/ParCzech/PipeLine/FileManager.pm)). It anotates tei file with [UDPipe2 LINDAT service](http://lindat.mff.cuni.cz/services/udpipe/run.php).

For Czech, you can run it in this way:
```
perl -I ../lib udpipe2.pl --model=czech-pdt-ud-2.6-200830 --output-file test_data_big.ann.xml --input-file test_data_big.xml
```
It annotates all text child within `<seg>` elements and allows annotation of one level subelement `<ref>`(it should contain the whole tokens) in default settings.

You can try it. Use it wisely - please don't overload our service. It is sending 100k requests and have a sleep 1 second after each request.

Development is still in progress and it is probably not fully compatible with ParlaMint. Bug reports are welcomed.

**Comment by TomazErjavec** [comment]
Additionally, Nikola sent information about the script he uses, which has been added in 18af580.

**Comment by matyaskopp** [comment]
It seems that [Classla](https://github.com/clarinsi/classla-stanfordnlp) uses different names for [extended syntactic relations](https://universaldependencies.org/ext-dep-index.html) - the relations with colon. Classla uses `_` instead of `:`.

I am using notation with a colon that forces me to use a little trick in the definition of ud-syn prefix:
```
<prefixDef ident="ud-syn" matchPattern="(.+)" replacementPattern="#xpath(//*[@xml:id = replace('$1',':','_')])">...</prefixDef>
```

Is it a correct way how should it be handled?

**Comment by TomazErjavec** [comment]
> It seems that Classla uses different names for extended syntactic relations - the relations with colon. Classla uses _ instead of :.

This is - at least partially - my fault, as in the TEI it is indeed better to use underscore instead of colon, exactly because of the prefixDef, i.e. the TEI extended pointer syntax presupposes that the colon is used to separate the prefix from the value proper, so it is better not to have colons in the value. But, yes, it is not necessary for the raw CLASSLA output to use underscores. Maybe an issue on https://github.com/clarinsi/classla-stanfordnlp/issues ?

> I am using notation with a colon that forces me to use a little trick in the definition of ud-syn prefix:

The V1 languages all use underscore in the values, so I suggest you do the same, i.e. just replace colons with underscores when converting to TEI, so we all have the same simple pattern,  e.g. in ParlaMint-PL/ParlaMint-PL.ana.xml:

```
            <prefixDef ident="ud-syn" matchPattern="(.+)" replacementPattern="#$1">
               <p xml:lang="pl">Prywatne URI z tym prefiksem wskazują na elementy po ich nazwie. W tym dokumencie są to lokalne odesłania do kategorii taksonomii UD-SYN w głównym nagłówku korpusu TEI.</p>
               <p xml:lang="en">Private URIs with this prefix point to elements giving their name. In this document they are simply local references into the UD-SYN taxonomy categories in the corpus root TEI header.</p>
            </prefixDef>
```
(and, yes, given that the definitions are in the same XML document, prefixDef is not really needed, we could just write `#acl` instead of `ud-syn:acl`, but it seemed nicer for consistency reasons, i.e. that all linguistic annotation values have a prefix.)

**Comment by TomazErjavec** [comment]
There does not seem to be anything to do in connection with this issues, so I am closing it.
