### ISSUE TITLE
NO text submission

### ISSUE THREAD

**Issue by tungland** [clarin-eric/ParlaMint#513]
Hi 

I didn't hear back about the current NO sample, but I think I managed to implement all your feedback. If you think we are ready to proceed with submission of the NO data, below is a link to the full Norwegian ParlaMint without the .ana files. I think we where asked to submit like this first?

NO text version download:
[link](https://drive.google.com/file/d/1TxPOwLLZfHVNyJLSikh6QwUciA1PHPW9/view?usp=share_link)

**Comment by matyaskopp** [comment]
> I didn't hear back about the current NO sample, but I think I managed to implement all your feedback. If you think we are ready to proceed with submission of the NO data, below is a link to the full Norwegian ParlaMint without the .ana files. I think we where asked to submit like this first?

Sorry, I haven't noticed that you have implemented all the suggested changes. I will go through it today and let you know if it is ok.

**Comment by tungland** [comment]
Thanks!

**Comment by TomazErjavec** [comment]
> submission of the NO data, below is a link to the full Norwegian ParlaMint without the .ana files. I think we where asked to submit like this first?

Indeed yes. I downloaded the files and had a look (cf. also the instructions at the end of https://github.com/clarin-eric/ParlaMint/blob/main/CONTRIBUTING.md):

* you have some half finished add-common-content/ directory there, not needed or really wanted
* the name of the top level dir should be ParlaMint-NO.TEI rather than ParlaMint-NO (and, for the annotated version, once ready, should be ParlaMint-NO.TEI.ana)
* the component files should be in year directories, e.g. 1998/ParlaMint-NO_1998-10-01-lower.xml (you can use ParlaMint/Scripts/dirify-parlamint.pl to do this). The root file should have appropriatelly modified XIncludes.
* the files in hte XInclude are in some random order, they should be in chronological order
* in the root file the title says SAMPLE, but this is no longer a sample
* in the root file you have the list of sessions, which is fine, but you should also have the list of terms
* all the taxonomies have been translated, it seems: very nice!
* your terms are defined as `Term 1997-2001`; most countries have them like `Term 12` or similar but if NO likes to label them by years, also ok (so, just mentioning this)
* you have things like `<affiliation from="2021-10-01" to="2025-09-30" ref="#ST" role="member"/>`, is this a mistake? You can't really know what the future holds, so maybe just leave out the to attribute
* you have only coalitions defined, but no oppositions. We already with some other countries have problems defining what it actually means to be in opposition, is it the same in NO? Could you come up (and implement) any useful definition of opposition?
* in the segments you have like ` petroleumssektoren<note type="comment">(SDØE)</note>og`, which seems dangerous, if you remove note (as you will for linguistic processing) you get `petroleumssektorenog`. So, it would be safer to put a space before notes and similar.
* you have notes like `<note type="comment">[10:06:32]</note>`; in case you have the energy, there are more precise labels for notes like this, i.e. `<note type="time">[10:06:32]</note>`

The above I noticed going through the files; I also ran the "prepare ParlaMint for distribution" process, and the full log is at https://nl.ijs.si/et/tmp/ParlaMint/Repo/ParlaMint-NO.log, maybe you could have a look. Don't worry abou the errors about missing .ana files, which is of course normal, as they are, well, missing so far.

**Comment by tungland** [comment]
Thanks for the feedback Tomaz, I will get on it promptly. 

> you have things like <affiliation from="2021-10-01" to="2025-09-30" ref="#ST" role="member"/>, is this a mistake? You can't really know what the future holds, so maybe just leave out the to attribute

It is not a mistake as such: it is like this in the source data. In Norway the status of MP is protected, and there are very few scenarios where a person would lose this status, the main one being death. There is no system for by-elections and the like, or for suspending MPs convicted of crimes. There is also no system for dissolving the parliament itself, elections are always regular. If a person was unable to meet, their deputy would take their seat, but they would not lose their status. But if this looks odd I could remove the "future" dates. 

> you have only coalitions defined, but no oppositions. We already with some other countries have problems defining what it actually means to be in opposition, is it the same in NO? Could you come up (and implement) any useful definition of opposition?

I don't really know what this would look like. There is no formal status of opposition party. Minority governments are the norm, and they will usually have to bargain in Parliament to pass legislation. Under the previous PM we saw a system where there was a formal agreement between the government and some parties outside to government about collaborating on legislation, but the norm over the past few decades is to seek more ad-hoc collaborations. 

> you have notes like <note type="comment">[10:06:32]</note>; in case you have the energy, there are more precise labels for notes like this, i.e. <note type="time">[10:06:32]</note>

I'll see if I can do something about this. But I think we are running a little low on time?

**Comment by TomazErjavec** [comment]
> It is not a mistake as such: it is like this in the source data. In Norway the status of MP is protected. ... But if this looks odd I could remove the "future" dates.

Well, it does look odd to me but if it is in the source data, migt as well leave it, it can make a nice footnote in a paper :)

Same for opposition - given that you don't have this concept. For AT, I think, they decided to mark with opposition only those that are clearly typically against the governemt agenda. In case @matyaskopp has an error, if it is missing, I guess it should be changed to warning...

As for time, (in both senses), there is still most of December left, again, up to you. Note types are somewhat a mess anyway.

**Comment by matyaskopp** [comment]
> > It is not a mistake as such: it is like this in the source data. In Norway the status of MP is protected. ... But if this looks odd I could remove the "future" dates.
> 
> Well, it does look odd to me but if it is in the source data, migt as well leave it, it can make a nice footnote in a paper :)
> 
> Same for opposition - given that you don't have this concept. For AT, I think, they decided to mark with opposition only those that are clearly typically against the governemt agenda. In case @matyaskopp has an error, if it is missing, I guess it should be changed to warning...
> 
> As for time, (in both senses), there is still most of December left, again, up to you. Note types are somewhat a mess anyway.

no, it produces error only if there is no type of `coalition` or `opposition` relation.
https://github.com/clarin-eric/ParlaMint/blob/16812d4742d99b0387a7b779eb9ebae3f9cc45b7/Scripts/parlamint-lib.xsl#L353-L359
So NO sample is ok because it has a `coalition`.

I guess this can be done better (stricter):
- missing `coalition` -> ERROR
- missing `opposition` -> WARNING

@TomazErjavec should I change it?

**Comment by tungland** [comment]
@TomazErjavec @matyaskopp here is the revised version of the text part. We are also ready to make the full submission with .ana files.

[link](https://drive.google.com/file/d/1jFuHZmKnnhe_shlzKazyjkgkzVAGBjPX/view?usp=sharing)

**Comment by TomazErjavec** [comment]
Thanks, the log file is [here](https://nl.ijs.si/et/tmp/ParlaMint/Repo/ParlaMint-NO.log).
There is one error, a div without any u:
```
/project/corpora/Parla/ParlaMint/V3/Master/ParlaMint-NO.TEI/2005/ParlaMint-NO_2005-04-19.xml:124:16: error: element "div" incomplete; missing required element "u"
```
You can have [div](https://clarin-eric.github.io/ParlaMint/#TEI.div)s witout u, but then they should have `@type="commentSection"`

The covid subcorpus start date seems to be wrong, but I fix that:
```
WARN ParlaMint-NO_2019-11-05: fixing subcorpus to covid for date 2019-11-05
...
```
You also have some trailing spaces in catDesc (grep for "Trailing space in catDesc").

You don't have opposition, but we discussed that, so it is ok.

So, maybe you could fix the remaining, and then send both versions of the corpus.

**Comment by tungland** [comment]
Thanks for the quick feedback @TomazErjavec . I completely forgot to implement the "commentsection" in the full corpus! Sorry for the trouble. I'm out of office this afternoon but will share the full corpora tomorrow.

**Comment by tungland** [comment]
Preparing to submit the full corpora, but having an issue with the add-common-content script https://github.com/clarin-eric/ParlaMint/issues/554

**Comment by tungland** [comment]
I couldn't get the add-common-content to work on the full corpus, but maybe we could still check if the corpus is otherwise ok just to get the ball rolling?

Here is the revised ParlaMint-NO.TEI and the ParlaMint-NO.TEI.ana:
[ParlaMint-NO.TEI](https://drive.google.com/file/d/1WhE03f_7wbit-ecFk9f7-R5-0ihYKQTt/view?usp=sharing)
[ParlaMint-NO.TEI.ana ](https://drive.google.com/file/d/1KdP5YDn_3_Khi8sgzN0wis5ZHQHGok1X/view?usp=sharing)

**Comment by TomazErjavec** [comment]
The add-common-content question is for @matyaskopp, although I have to say, that it actually does not affect the final corpus, as my "prepare for distribution" script also modifies/adds this content to the corpus you send - and, if it is already ok, the operation is a no op. The idea here is more that we don't make changes in your corpus.

So, good that you sent the corpus. Will download (but it takes forever as it is on the cloud, and I have to transfer it twice and that from home) and process - will let you know how it went, probably tomorrow.

**Comment by tungland** [comment]
Ok! Thanks!

**Comment by TomazErjavec** [comment]
The log is at https://nl.ijs.si/et/tmp/ParlaMint/Repo/ParlaMint-NO.log
grep for -i error and -i warn
What I noticed:
- you forgot the "SAMPLE" in the titles, it isn't a sample anymore
- you have empty lemmas (and somewhat weird NEs), e.g. 
```
                     <name type="ORG">
<w xml:id="ParlaMint-NO_1999-01-27.ana.segd845e2006.1.12" lemma="" msd="UPosTag=DET|Case=Gen">s</w>
                     </name>
```
- and some syntax errors (but these qualify as warnings, as it is difficult to fix this if the annotation software produces bad parses):
```
[Tree number 443 on line 11778 Sent ParlaMint-NO_1999-01-21-lower.ana.segd242e416.4]: [L2 Syntax non-tree] Non\
-tree structure. Words 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20 are not reachable from the root 0.
[Tree number 443 on line 11778 Sent ParlaMint-NO_1999-01-21-lower.ana.segd242e416.4]: [L2 Format skipped-corru\
pt-tree] Skipping annotation tests because of corrupt tree structure.
```
I hope it won't be too hard to fix this.

You can also find your corpus under https://www.clarin.si/noske-beta/parlamint30.cgi/ (dev / alfabetagama) and you could take a look if it meets your expectionations - sometime the concordancer reveals bug it is hard otherwise to see in the data.

**Comment by tungland** [comment]
Thank you for you feedback @TomazErjavec 

> you forgot the "SAMPLE" in the titles, it isn't a sample anymore
It's not "SAMPLE" that's causing it, but the lack og .ana extension I believe. Should be easy to add. Weird that validation in my end did not pick this up though. 

> you have empty lemmas (and somewhat weird NEs), e.g.
This is caused by a error in the text. Difficult to get all of those. Seems it could not find a lemma for this (rightly, it's not valid Norwegian). I could set the lemmas to be equal to the tokens in the cases where the lemma fields are empty. But the ORG is not possible to do anything about I'm afraid. 

>  and some syntax errors (but these qualify as warnings, as it is difficult to fix this if the annotation software produces bad parses):

Yeah, this seems to be an artifact of the annotation. Don't really know what to do about that.

**Comment by TomazErjavec** [comment]
> It's not "SAMPLE" that's causing it, but the lack og .ana extension I believe. Should be easy to add. Weird that validation in my end did not pick this up though.

Strange indeed. Well, as long as it can be fixed...

> I could set the lemmas to be equal to the tokens in the cases where the lemma fields are empty. 

Yes, probably the best solution.

> But the ORG is not possible to do anything about I'm afraid.

OK.

> Yeah, this seems to be an artifact of the annotation. Don't really know what to do about that.

Probably nothing...

**Comment by tungland** [comment]
@TomazErjavec Here is a new download link. Hope I got it all this time!

[link](https://drive.google.com/file/d/1asSIjyBPPb69fnFZo39q-hS71AOBnUsA/view?usp=sharing)

> You can also find your corpus under https://www.clarin.si/noske-beta/parlamint30.cgi/ (dev / alfabetagama) and you could take a look if it meets your expectionations - sometime the concordancer reveals bug it is hard otherwise to see in the data.
This looks very nice!

**Comment by TomazErjavec** [comment]
The log over the latest data is at https://nl.ijs.si/et/tmp/ParlaMint/Repo/ParlaMint-NO.log

Warnings about subcorpus and words, although I fix this.
Only errors left are those about syntax, but, as we said, not much can be done there. 
Although I should note some of them are nasty, e.g.:
```
[Line 27642 Sent ParlaMint-NO_2004-04-21.ana.segd2627e1413.1]: [L2 Syntax head-self-loop] HEAD == ID for 1
```
which means that software that processes such as parse could loop. Ah well.

**Comment by tungland** [comment]
> [Line 27642 Sent ParlaMint-NO_2004-04-21.ana.segd2627e1413.1]: [L2 Syntax head-self-loop] HEAD == ID for 1

We could have a look at it for the next round. The problem here is that it references itself in some way?

**Comment by TomazErjavec** [comment]
> We could have a look at it for the next round. The problem here is that it references itself in some way?

It seems that way, yes.

**Comment by tungland** [comment]
@TomazErjavec @matyaskopp Happy new year! Is there anything else needed for the NO data for ParlaMint 3.0?

**Comment by matyaskopp** [comment]
@tungland
if you have fixed this: https://github.com/clarin-eric/ParlaMint/issues/568, then please update your sample with new pull request and then we can close your issues

**Comment by tungland** [comment]
@matyaskopp in this issue https://github.com/clarin-eric/ParlaMint/issues/561#issuecomment-1364028247 I was told this issue was not blocking the release of ParlaMint 3.0. What is the plan for 3.1 vis-a-vis 3.0? Changing the language code is a relatively minor issue, but if there were any other issues that would need to be solved by me between 3.0 and 3.1 I would be very happy if they could be bundled together.

**Comment by tungland** [comment]
But if this is the only remaining requirement, I will proceed with creating a new version of the corpus.

**Comment by tungland** [comment]
@TomazErjavec @matyaskopp I updated the language codes. Sent a new pull request with the updated sample. Below is the download links for the updated corpus. I have also written the documentation for the Norwegian data in the shared document.

I hope we can now consider the Norwegian corpus delivered.

[ParlaMint-NO.TEI](https://drive.google.com/file/d/1IHP3840FHB2TQYCFoEqu-0Q5aUx-zbf1/view?usp=sharing)
[ParlaMint-NO.TEI.ana](https://drive.google.com/file/d/1bV5BnS3DgrZKriAU4X5XZs8Gs_SwvTyl/view?usp=sharing)

**Comment by TomazErjavec** [comment]
> Below is the download links for the updated corpus. 

Got it, thanks, and processed it, cf. the [log](https://nl.ijs.si/et/tmp/ParlaMint/Repo/ParlaMint-NO.log), and the updated corpus on the [beta concordancer](https://www.clarin.si/noske-beta/parlamint30.cgi/):
* you forgot to update the language definitions in the .TEI version of the corpus, so this causes many errors. But I can fix it localy, no need to resend the files because of this.
* CoNLL-U validation reports (only) 1 error: `[Tree number 443 on line 11778 Sent ParlaMint-NO_1999-01-21-lower.ana.segd242e416.4]: [L2 Syntax non-tree] Non-tree structure. Words 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20 are not reachable from the root 0.` For one bad sentence parse, I don't think its worth complicating with fixing this.
* as for warnings, we have (and know about) the missing oppostions, the rest is standard stuff which I fix.

So, as far as I am concerned, corpus is ok for 3.0. But I guess you should update the sample on Git with corrected TEI root with the correct langUsage.

**Comment by matyaskopp** [comment]
I have found one strange thing. You have both upper and lower house and many documents without houses:
https://www.clarin.si/noske-beta/parlamint30.cgi/wordlist?corpname=parlamint30_no;wlmaxitems=1000;wlattr=speech.house;wlminfreq=1;include_nonwords=1;wlsort=f;wlnums=docf
if there are shared sittings (lower+upper) I think they should be annotated with both

**Comment by tungland** [comment]
> I have found one strange thing. You have both upper and lower house and many documents without houses:
https://www.clarin.si/noske-beta/parlamint30.cgi/wordlist?corpname=parlamint30_no;wlmaxitems=1000;wlattr=speech.house;wlminfreq=1;include_nonwords=1;wlsort=f;wlnums=docf
if there are shared sittings (lower+upper) I think they should be annotated with both

@matyaskopp I disagree with this. Constitutionally there never were such things as upper and lower houses in Norway. The Parliament was de jure one body. Pre 2009 the parliament had two different departments which under some circumstances would act similar to upper and lower houses. But the main chamber acted as one. We had a previous discussion about this here: https://github.com/clarin-eric/ParlaMint/issues/473#issuecomment-1354946806

**Comment by tungland** [comment]
> you forgot to update the language definitions in the .TEI version of the corpus, so this causes many errors. But I can fix it localy, no need to resend the files because of this.

Oops. I did not forget about this in the sample though, so that one is alright already. Thanks!

**Comment by matyaskopp** [comment]
> @matyaskopp I disagree with this. Constitutionally there never were such things as upper and lower houses in Norway. The Parliament was de jure one body. Pre 2009 the parliament had two different departments which under some circumstances would act similar to upper and lower houses. But the main chamber acted as one. We had a previous discussion about this here: [#473 (comment)](https://github.com/clarin-eric/ParlaMint/issues/473#issuecomment-1354946806)

I refreshed it in my memory, so the main part of texts should be classified with `#parla.uni` (because currently, Norway has a unicameral system), but you don't have a unicameral parliament organization.
I think we want to have information about where the speeches were recorded. I can imagine that you can extend your corpus in future with various parliamentary committee meetings:
https://github.com/clarin-eric/ParlaMint/blob/5deaeed5ae792f3ba1726072298885b5b64a6d64/Data/ParlaMint-NO/ParlaMint-NO.xml#L233-L242
 and it would be impossible to distinguish where the topic was discussed.
I am not insisting on fixing this because I am not sure about that. I just wanted to point out that it is strange to skip this classification.

**Comment by tungland** [comment]
Thanks for your feedback @matyaskopp 

> I think we want to have information about where the speeches were recorded. I can imagine that you can extend your corpus in future with various parliamentary committee meetings:

I'm not sure I understand this. When you say "where the speeches were recorded" do you mean physical location? Or with which body/department?

**Comment by matyaskopp** [comment]
> Or with which body/department?

I meant which organization/department:
- it consequently says who is present (or at least should be present) at the meeting - the listeners of the speeches 
- various organizations have different scopes of authority

**Comment by tungland** [comment]
@matyaskopp Ah so if there is a committee, it would not be clear if it was spun out from the "lower house", the "upper house" or the joint body?

**Comment by matyaskopp** [comment]
ParlaMint schema technically allows storing proceedings from committees, so it should be clear which organization the sitting belongs to.
In CZ we have both chambers, but I have proceedings only from the lower house - still I am saying in every sitting that the organization that managed the sittings is the lower house:
https://www.clarin.si/noske-beta/parlamint30.cgi/wordlist?corpname=parlamint30_cz;wlmaxitems=1000;wlattr=speech.house;wlminfreq=1;include_nonwords=1;wlsort=f;wlnums=docf

Now I checked @TomazErjavec script and even if you fill `#parla.uni` it would still leave speach.house empty:
https://github.com/clarin-eric/ParlaMint/blob/5deaeed5ae792f3ba1726072298885b5b64a6d64/Scripts/parlamint-lib.xsl#L172-L202
So it does not allow `parla.committee` meetings (but I believe BE will need it: https://github.com/clarin-eric/ParlaMint/issues/496#issuecomment-1372343737 )

so, @tungland , forget what I wrote, this will need discussion between me and @TomazErjavec (and it will be probably postponed for next generations of ParlaMint)

**Comment by TomazErjavec** [comment]
I won't go into the rest, but I do agree with:

> this will need discussion between me and @TomazErjavec (and it will be probably postponed for next generations of ParlaMint)

@matyaskopp, maybe you could open an issue with milestone 3.1 to address the above, ie. "even if you fill #parla.uni it would still leave speach.house empty". This seemed to make sense at the time, but maybe it could be done differently, esp. if we have commitee meetins as well.

**Comment by tungland** [comment]
@TomazErjavec @matyaskopp OK. But then we are done with ParlaMint-NO for now, and we can close this issue?

**Comment by TomazErjavec** [comment]
As far as I am concerned, yes.

**Comment by tungland** [comment]
Super!
