### ISSUE TITLE
Element for Acting Ministers in government metadata?

### ISSUE THREAD

**Issue by AnnaParla** [clarin-eric/ParlaMint#548]
@matyaskopp Is there a TEI Schema element to mark an acting minister or acting prime minister? For instance, in a few Ukrainian governments some officials served in the role of a minister, prime minister or even president but never fully entered into office in conformity with the law.

**Comment by matyaskopp** [comment]
I can see these options for how it can be implemented

 1. adding new affiliation roles `actingMinister`, `actingHead`,...
 2. creating a taxonomy `affiliation.role` and  category `affiliation.role.acting`
 ```XML
      <affiliation ref="#GOV.UA"
                   role="minister"
                   from="2020-03-10"
                   to="2020-06-04"
                   ana="#GOV.UA.Shmyhal #affiliation.role.acting">
         <roleName xml:lang="uk">Міністр культури, молоді та спорту України</roleName>
         <roleName xml:lang="en">Minister of Culture, Youth and Sports</roleName>
      </affiliation>
```
 3. use always `<roleName>` element inside `<affiliation>` and add the prefix `acting ` to the text:
 ```XML
      <affiliation ref="#GOV.UA"
                   role="minister"
                   from="2020-03-10"
                   to="2020-06-04"
                   ana="#GOV.UA.Shmyhal">
         <roleName xml:lang="uk">в.о. Міністр культури, молоді та спорту України</roleName>
         <roleName xml:lang="en">acting Minister of Culture, Youth and Sports</roleName>
      </affiliation>
```

I don't like option 1 because if you don't care if the minister is acting or not, then you should search for two roles in queries: `minister` OR `actingMinister`

The second option is probably the best, and it can also be used together with option 3. 
But this taxonomy is quite poor - with one category, but it makes sense to extend it to other types of person roles:
- `affiliation.role.acting`
- `affiliation.role.exile`
- `affiliation.role.shadow`

@TomazErjavec, @katjameden, 
any suggestions?

**Comment by katjameden** [comment]
Personally, I agree that option 2 is probably better, since (as you explained) this would prevent confusion of roles in the queries. In addition, I am pretty sure there are some exceptions in other parliamentary systems that could be addressed by this (if implemented in the next corpora versions). For example, in SI there are cases where the prime minister can be temporarily appointed as a minister, or a minister can be appointed as a temporary minister in another ministry (for maximum 3 months).

To illustrate: prime minister Miro Cerar was a temporary minister of the Ministry of Education, Science and Sports for a period of about one month. This even happened twice within one government term. 
Similarly, the current minister of Public Administration is also temporarily head of the Ministry of Internal Affairs).

If this falls under the taxonomy topic (and if it makes sense), this could be added as `affiliation.role.temp`, `affiliation.role.substitute` or similar.

**Comment by TomazErjavec** [comment]
OK, this has been solved for UA. As for the rest (i.e. making a better set of roles) would definitelly require a new issue and lost of work. So, closing this issue.
