### ISSUE TITLE
distro Makefile do not repport some errors

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#703]
when there is no space after the word error, then it is not reported:
https://github.com/clarin-eric/ParlaMint/blob/c68b7fe2bc4f27a85e8e8dbe08545035d0dc179e/Distro/Makefile#L85

eg error in CZ corpus: 
```
ERROR[01] ParlaMint-CZ-listPerson affiliation collision: (2013-11-06T00:00:00 --- 2017-10-26T23:00:00) is inside (2013-10-30T00:00:00 --- 2017-10-26T23:00:00) affiliation member-#parliamentaryGroup.ODS
```
I have no idea how these errors survived all the validations...

**Comment by TomazErjavec** [comment]
Yes, in the meantime I've noticed this too and in fact fixed it, but didn't commint the Distro/Makefile, sorry. Did it now.
But, in general, it is a problem because different scripts report errors differenty, like "ERROR: " (me), "ERROR[" (you), "error" (CoNLL validation). Now the grep does simple -i "error", so everything is reported, including "terror" :) But I guess better too much than too little...

**Comment by TomazErjavec** [comment]
As this has been fixed, as far as possible, closing.
