### ISSUE TITLE
Strange importing in schema

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#74]
I am not sure if cycle import is valid in XSD, but it is at least strange in this case:

https://github.com/clarin-eric/ParlaMint/blob/99f6b182f407287352957969e9d61fccc2c41002/Schema/xi.xsd#L3

https://github.com/clarin-eric/ParlaMint/blob/99f6b182f407287352957969e9d61fccc2c41002/Schema/xml.xsd#L3

related to #73

**Comment by TomazErjavec** [comment]
Weird. I make the XSD with trang, just because it's simple to do. I've never even used it, but did try now in Oxygen, and it doesn't mind the cycle, however:
```
System ID: C:\Users\tomaz\Documents\GitHub\ParlaMint\Schema\ParlaMint-TEI.xsd
Main validation file: C:\Users\tomaz\Documents\GitHub\ParlaMint\ParlaMint-BE\ParlaMint-BE.ana.xml
Schema: C:\Users\tomaz\Documents\GitHub\ParlaMint\Schema\ParlaMint-teiCorpus.ana.xsd
Engine name: Xerces
Severity: error
Problem ID: cos-nonambig
Description: "http://www.tei-c.org/ns/1.0":note and "http://www.tei-c.org/ns/1.0":comment (or elements from their substitution group) violate "Unique Particle Attribution". During validation against this schema, ambiguity would be created for those two particles.
Start location: 384:6
End location: 384:20
URL: http://www.w3.org/TR/xmlschema-1/#cos-nonambig
```
Martin Kay (of Saxon fame) has [something](https://stackoverflow.com/questions/46068463/unique-particle-attribution-error)  to say on this.

It is also true that trang complains already in the XSD generation:
```
ParlaMint/Schema/ParlaMint-TEI.ana.rng:135:15: warning: choice between attributes and children cannot be represented; approximating
```

To cut this knot, I will just delete the XSD, anybody that wishes to validate with the schema, should just use RelaxNG!
