### ISSUE TITLE
Inserting coalition/opposition into the corpora

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#77]
In cd103d7 I made a premilinary conversion from the TSV exported G'spreadsheet into a format that could be inserted into the root files of the corpora, in particular (cf. the [Makefile](https://github.com/clarin-eric/ParlaMint/blob/main/Parties/Makefile)):

* Renames the original exported file (which contains spaces) into a nicer one and converts it to Unix format.
* Uses the new [stylesheet](https://github.com/clarin-eric/ParlaMint/blob/main/Scripts/coaloppo-tsv2xml.xsl) to take the TSV file and the [ParlaMint root](https://github.com/clarin-eric/ParlaMint/blob/main/ParlaMint.xml) (or, rather, it's XIncluded corpus roots) to convert it into the appropriate `<relation>` elements, also somewhat validating the input
  * validation: is the input data well-formed; do the party IDs actually exist in the country corpus root. 
  * conversion: in addition to the simple format conversion, the script also attemps to insert the term when the coalition/opposition party was in existence into `relation/@ana`.

The input and output files (and Makefile) are in the [Parties](https://github.com/clarin-eric/ParlaMint/tree/main/Parties) directory.

The idea is that, when the input for a particular country/corpus is taken to be finished, the G'sheet is exported, the conversion run, and, if there are no errors messages for the country in the [validation log](https://github.com/clarin-eric/ParlaMint/blob/main/Parties/ParlaMint-relations.log), the `<relation>` elements for the country in the **[output file](https://github.com/clarin-eric/ParlaMint/blob/main/Parties/ParlaMint-relations.xml)** are slightly edited and included into the two corpus roots. 

The editing concerns:
* removing the `relation/@n` attribute which gives the name of the country
* checking the terms in `relation/@ana` (e.g. for parliaments with two houses)
* checking of the `relation/@passive` is ok for oppositions, if it isn't, the `org[@role = 'government']` would need to be added to the corpus roots, at least if we continue to encode it as suggested in #76.

Apart from the already mentioned bad NL parties, the  log also contains warnings about "unknown":
https://github.com/clarin-eric/ParlaMint/blob/cd103d76452018390f4c63296892295952174a36/Parties/ParlaMint-relations.log#L1-L5
The reason is that the instructions that Ruben wrote also say that "unknown" is a valid option but I am at a loss how to interpret this information ((I did comment on this in the G'doc, but the comment was resolved without resolving the issue...), i.e. what does it mean, and, in particular, what is the difference if a party in marked as "unknown" versus that a party is simply not included in a coalition/opposition. So, to my mind, the "unkown" can simply be deleted.

Comments on the above plan and issues, in particular, what to do with corpora that are lacking the "governemt organisation" and what to do with "unknown" appreciated.

**Comment by matyaskopp** [comment]
### `unknown`

The more I am thinking about the coalition/opposition, the more I am confused. For Czech can be 100 % sure who is in a coalition, because the parties signed an agreement and it is possible to find it on the government web.

Everything else is based on some rumor, journalist's news, and my interpretation. But we don't want to add to our data a new mess.
Are we allowed to make such a decision?

The `unknown` in our case stands for these two situations:

1. period between the beginning of term and nominating government by the president (in this time we have government from the previous term in demise)
2. declared silent support of the government by communists (based on news)

**Comment by TomazErjavec** [comment]
> Everything else is based on some rumor, journalist's news, and my interpretation. But we don't want to add to our data a new mess. Are we allowed to make such a decision?

Yes, I agree it is a mess, and Ruben and me didn't find a good solution. To me it seems that it is better to have (somewhat) sloppy information than none at all, as most people will presumably be looking at summary info (like the difference in vocabulary) in comparing colaition / opposition, rather than to which a particular party belongs in a given timeframe.

So, I would go for rumours and subjective interpretations on the question of opposition. But, yes, it would be good to record this, probably in the [interpretation](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-interpretation.html) element. Which would mean asking everybody to add this element to their TEI headers, well, or just me doing if in the finalization - under the assumption that everybody actually does this interpretations the same. Sigh, we have opened a big can of worms with this addition...

**Comment by rubenros1795** [comment]
I agree that leaving the ```unknown``` is better. I also commented this in the G-doc now. 

> The more I am thinking about the coalition/opposition, the more I am confused. For Czech can be 100 % sure who is in a coalition, because the parties signed an agreement and it is possible to find it on the government web.

I realize this might result in more confusion, but when deciding over matters like these, the question whether parties deliver ministers (and are thus actually constituting the government) might be an indicator to distinguish between coalition participation and "silent support"? In the case of the Czech Republic this would mean that the communists are not marked as coalition.

**Comment by calzada** [comment]
Tomaz,
I have really been thinking about this issue and as I told you this is a bit confusing in the Spanish case. So I am going to leave it as it is if it is not too much of a problem for you.
Best for now,
mc

**Comment by TomazErjavec** [comment]
> So I am going to leave it as it 

Well, it does seem a shame that SP will be one of the few countries without this very useful information. But, if opposition is a problem, could you not put in at least the coalitions - from a brief scan of the following, I think it shouldn't be more than a couple of hours work:
* https://en.wikipedia.org/wiki/First_government_of_Mariano_Rajoy
* https://en.wikipedia.org/wiki/Second_government_of_Mariano_Rajoy
* https://en.wikipedia.org/wiki/First_government_of_Pedro_S%C3%A1nchez
* https://en.wikipedia.org/wiki/Second_government_of_Pedro_S%C3%A1nchez

But, ultimately, it is up to you of course.

**Comment by calzada** [comment]
Dear Tomaz,

I am really unsure about what I have to do. I have been trying to understand it and still I do not quite understand. Do I need to fill in this document: 

ParlaMint-coaloppo.tsv

If this is the case, the safest thing to do is to use a very strict definition of coalition as parties in the government. In this sense, there has only been one coalition in government. And this is in this final legislature (<meeting n="14" corresp="#CD" ana="#parla.term #CD.14">Term 14</meeting>) from 2019-12-03 up to the present moment (and in our case until 31/12/2020). So I will include this. I am going to work with this assumption. Let's see how this goes. Because in Spain the same party has many different names according to their regions. So I will now have a look and check which parties actually make up the coalition. It is only the Socialist and the Far-Left (UP) but they may go under many different names. 

Let me try, along these lines.

best

mc

**Comment by TomazErjavec** [comment]
> Do I need to fill in this document: ParlaMint-coaloppo.tsv

Um, no, Ruben sent around the Google sheet that you are supposed to fill out, will send you the link via email.

**Comment by calzada** [comment]
Done, Tomaz. I have filled in the spreadsheet with the only governmental coalition. I have done nothing for the opposition since the rest of the parties would be in the opposition. But if you need me to do so. I can fill in the opposition for term 14. 
Regarding, the rest of the terms, would you like me to do anything. Since there are no more governmental coalitions. Would you like me to put all parties in opposition?
I am willing to do so. But this time, I will not do it before asking. ;-)
Thank you for your patience.
Best for now,
mc

**Comment by TomazErjavec** [comment]
> I have filled in the spreadsheet with the only governmental coalition.

Great, thanks!

>  I have done nothing for the opposition since the rest of the parties would be in the opposition. But if you need me to do so. I can fill in the opposition for term 14.

Yes, that would be good.

> Regarding, the rest of the terms, would you like me to do anything. Since there are no more governmental coalitions. Would you like me to put all parties in opposition?

This I don't understand, are you saying that nobody was in coalition before 2019-12-03? Who were the parties in oppostion to then?

**Comment by TomazErjavec** [comment]
Today is the official data freeze for V2.0, but I would like to give everybody the chance to correct the relations made on the basis of the Google sheet which you can find on https://github.com/clarin-eric/ParlaMint/blob/main/Parties/ParlaMint-relations.xml.
@calzada, note that I have not put in the ES data, you are a special case, and I will do that once you let me know you are finished with the Google Sheet.

So, if you find any errors, pls. send your corrected `<listRelation>` by tomorrow (6th May) and I will insert it into your ParlaMint-XX.xml and ParlaMint-XX.ana.xml. If your prefer, you can also send me the corrected two root files.

In the meantime, I will insert the current data into your root files and start the validation and conversion process - if I get the corrected `<listRelation>` I will just do it again for the country in question.

**Comment by calzada** [comment]
To your question:

This I don't understand, are you saying that nobody was in coalition before 2019-12-03? Who were the parties in oppostion to then?

In Spain, before 2019/12/03 there was a one-party Government (NOT A COALITION, which by definition is a pact between parties) and the rest of the parties were the opposition. Some were more in favour of the governments than others bUT THEY WERE NOT IN A COALITION.

**Comment by TomazErjavec** [comment]
> In Spain, before 2019/12/03 there was a one-party Government (NOT A COALITION, which by definition is a pact between parties) 

OK, we are being a bit sloppy there, but in the ParlaMint universe, a "coalition" can be one party, there are other examples of this in the spreadsheet. So, this would make it in fact simple for you, just put this party into a "coaliton" and all the rest in "oppositon".

**Comment by calzada** [comment]
Dear Tomaz.
Done, for the Spanish side. Notice that I told you there were no other official governmental coalitions (apart from Term 14). But you will see a variety of parties under "coalition". These parties are in fact the same party (but for different regions in Spain). Also, we have some Members who act as representatives for regional Parliaments. I included them because they may have an opposing ideology to the power (or the same ideology to the party in power). Spanish politics is a bit messy. I realised when you posed this task. But I have tried to act in a consistent manner. 
I hope this is what you need.
Best for now,
mc

**Comment by TomazErjavec** [comment]
> Done, for the Spanish side.

Thanks a lot! I converted it (1 mistake with missing "party.", which I corrected in the G'seet) and looks ok as far as I can see, cf. https://github.com/clarin-eric/ParlaMint/blob/23de677a28f4ce8caee335df13031af88665f590/Parties/ParlaMint-relations.xml#L123-L177
More will be clear after conversion - but, if any problems, they can be corrected for V2.1.

**Comment by calzada** [comment]
Great Tomaz, 
Thanks so much for your help. ALWAYS. You are so thorough that indeed I wish I were like you. 
I have seen what you posted and indeed it seems perfect. 

Thanks again (and a million times).  

https://www.youtube.com/watch?v=z_aVNv_gNdM

Best

mc

**Comment by TomazErjavec** [comment]
This has been sorted as much as possible, closing.
