### ISSUE TITLE
UA: missing person

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/ParlaMint#836]
When validating ParlaMint-UA (4.0.1) I get
```
ERROR ParlaMint-UA_2003-07-09-m1: ERROR: Can't find local id for u/@who="#МиколаВасильовичОніщук.1959"
ERROR ParlaMint-UA_2003-07-09-m1.ana: ERROR: Can't find local id for u/@who="#МиколаВасильовичОніщук.1959"
```
This is a nasty errror, as it cause further processing (e.g. the creation the metadata TSV files) to fail, hence some down-conversion files are not produced. 

This person has only one utterance:
```
$ grep 'МиколаВасильовичОніщук.1959' */*.xml
2003/ParlaMint-UA_2003-07-09-m1.xml:            <u xml:id="ParlaMint-UA_2003-07-09-m1.u102" who="#МиколаВасильовичОніщук.1959" ana="#regular">
```

To be able to process the corpus I will, for now, remove the `u/@who` from this utterance (also in .ana).
If you know of a better solution, pls. let me know.

**Comment by matyaskopp** [comment]
@TomazErjavec 
this is probably caused by editing our spreadsheet, the person should be `МиколаВасильовичОніщук.1957`

![image](https://github.com/clarin-eric/ParlaMint/assets/5867995/70142a23-4bfc-42e9-924e-698b261836ef)

When you expand the ID in spreadsheet, the number at the end increases :-/

So the solution is to use `МиколаВасильовичОніщук.1957` in both versions

**Comment by TomazErjavec** [comment]
> So the solution is to use МиколаВасильовичОніщук.1957 in both versions

OK, I made this change, thanks!
