### ISSUE TITLE
Adding available metadata for parties

### ISSUE THREAD

**Issue by nljubesi** [clarin-eric/ParlaMint#859]
Hi everyone,

I would like for the current party metadata (e.g., [Build/Metadata/ParlaMint-parties-BA.tsv](https://github.com/clarin-eric/ParlaMint/blob/9693c7d6bea7a1c9df5db196061f49c39bca14dc/Build/Metadata/ParlaMint-parties-BA.tsv) for Bosnian parties) to be extended with metadata that you should have internally at your disposal, more concretely:

- the Wikipedia URL of the party
- the Chapel Hill Expert Survey ID

If there are any other metadata available, please let me know. For these two, they should just be added as two additional columns to the current tsv-s.

Thanks!

**Comment by TomazErjavec** [comment]
OK, did it. In line with the rest of metadata files, there are two variants, one in the original language, and one in English. If you need a combo, it should be simple enough to merge.
Also, I now output not only parties, but all organisations, as it seems more sensible. Again, if you need only `politicalParties` and `parliamentaryGroups` it is simple to just grep for those.
Currently, the complete set is output in one (or, rather, two) files, i.e. not by country. Again, it is simple to grep for the country of interest.
@nljubesi, let me know if anything is wrong in [ParlaMint-listOrg-en.tsv](https://github.com/clarin-eric/ParlaMint/blob/devel/Build/Metadata/ParlaMint-listOrg-en.tsv) or [ParlaMint-listOrg.tsv](https://github.com/clarin-eric/ParlaMint/blob/devel/Build/Metadata/ParlaMint-listOrg.tsv), if not, pls. close.

**Comment by nljubesi** [comment]
@TomazErjavec, thanks!

I would invite @mmochtak to have a look at this as well. @katjameden to give her opinion as well. This will be the starting point for your mapping to PartyFacts, right? There is a lot of information here already, and I see many usage scenarios. But we need to understand the opportunities and limitations.

These are the numbers / coverage I am getting for political parties and parliamentary groups:

political parties
- 316 overall defined
- 251 do not have the CHES ID
- some have duplicate CHES IDs (PS is both "Finns Party" in FI and "Partido Socialista" in PT), looking into CHES (https://www.chesdata.eu/s/CHES2019V3.csv), it seems that what is given here is the "party" attribute, not the "party ID", which is an abstract number, two questions here: 1. @mmochtak do you need CHES IDs for the validation of your method, or is it not important, 2. if @mmochtak answers yes, the question is whether @TomazErjavec or @katjameden  have those, or whether country ID with the "party" attribute is enough of an identifier
- 27 wikipedia URLs are missing, so wikipedia coverage is much better than CHES coverage (but also duplicate URLs do occur)

parliamentary groups
- 685 defined overall
- 464 do not have a CHES value
- 78 do not have a wikipedia link
- both have repetitions as above, wikipedia again seems to have better coverage

Let me know what you think, I guess @mmochtak first as you will be using the data. @TomazErjavec and @katjameden can clarify if this is needed. Thanks!

**Comment by katjameden** [comment]
Hi, I just want to add my two cents - firstly on the CHES `party_id`: I could probably re-process the CHES datasets to include this information if that's something that might be useful. However, I agree with Michal that the pipeline he suggested might be the way to go about this.

**Comment by nljubesi** [comment]
@katjameden Can you maybe clarify for me how political parties and parliamentary groups are used? Is there anything special that has to be said here, or are these just two types of orgs added to a speech?

**Comment by katjameden** [comment]
The `politicalParty` in the corpora denote the individual political parties, while `parliamentaryGroup` represent political parties in parliament (slv. poslanska skupina). In most cases (I can speak here mainly for the SI parliament) the parliamentary groups match 1:1 with the corresponding political party, but not always. For an individual political party in the list of organisations (listOrg) we can therefore use both `parliamentaryGroup `and `politicalParty` labels:

- since membership in the parliamentary group is more short-lived than the existence of a political party (even if political party/parliamentary group is a 1:1 match with the same name)
- in cases where there is no 1:1 match, where members of different political parties can form a parliamentary group, e.g. independent MPs (e.g. for SI, at least 3 MPs are required to form a group)
- the composition of a parliamentary group can change during its existence.
- Also some other exceptions (MPs/Ministers)...

However, according to the [guidelines](https://clarin-eric.github.io/ParlaMint/#sec-parties), the use of `parliamentaryGroup` is required in the corpus, while `politicalParty` is optional. Example: AT uses both labels in its [listOrg ](https://github.com/clarin-eric/ParlaMint/blob/devel/Build/Metadata/ParlaMint-listOrg.tsv), while BA only uses `parliamentaryGroup`.

So in cases where both labels are used (please correct me if wrong), these are considered as two separate organisations in listOrg.

I hope I've managed to write this coherently :)

**Comment by katjameden** [comment]
Oh, for usage: I'd say (@TomazErjavec correct me if I am wrong) that these two org types are more associated with the individual speaker and the temporal information of when said speaker was affiliated with the political party or parliamentary group (which is then in turn connected to the speech/utterance via speaker xml:id). This is explained in more detail in the [Guidelines](https://clarin-eric.github.io/ParlaMint/#sec-affiliation).

**Comment by nljubesi** [comment]
@mmochtak and I decided that he will try to map PartyFacts to Country+orgID (orgID is not unique in 20 cases). I have prepared the 685 parliamentary groups for him like this:

```
grep 'parliamentaryGroup' ParlaMint-listOrg.tsv | cut -f 1,3,4,5,9
```

Once we have something, we will report here.

**Comment by TomazErjavec** [comment]
@nljubesi, @mmochtak, I now corrected a bug (repeated header rows in the file) in [ParlaMint-listOrg-en.tsv](https://github.com/clarin-eric/ParlaMint/blob/devel/Build/Metadata/ParlaMint-listOrg-en.tsv) and [ParlaMint-listOrg.tsv](https://github.com/clarin-eric/ParlaMint/blob/devel/Build/Metadata/ParlaMint-listOrg.tsv), so just in case you have downloaded the previous version, pls. do so again.

As for the debate above:
* I think the CHES party ID (i.e. number) should be included in our TSV and esp. in the XML corpora, as any other dataset referring to CHES will most likely use this. So, @katjameden, could you re-do the generation of CHES TSV files including the ID (and, why not), the other first colums which also seems ot be missing. The new files should be exactly the same as the current ones in (Sources-TSV)[https://github.com/clarin-eric/ParlaMint/tree/devel/Build/Sources-TSV]/*/OrientationCHES-*.edited.tsv except for the added colums
* The fact that several parties have the same Wikipedia URL is most likely not an error, as Jure was quite careful in checking, but some parties rename themselves but have the same page in Wikipedia, @jureskubic, can you confirm?
* I hope the difference betwee politicalParty and parliamentaryGroup has been explain above, I should just add that both CHES and Wikipedia refer to political parties, not parliamentary groups, so we had some problems mapping their info onto the groups. Where the relation is 1:1, this is not problematic, in other cases they should be empty for CHES and averaged for Wikipedia, again, I hope I have this right @jureskubic?
* and, yes, it would be great to include party facts into ParlaMint.

**Comment by TomazErjavec** [comment]
>  So, @katjameden, could you re-do the generation of CHES TSV files including the ID (and, why not),

Because her files had it already, it was me that lost it on the way, sorry.
I fixed this now, also a lot of other things which were exposed in addressing this change, and the related changes to the script generating the listPerson.tsv file, cf. #860.
Note that the CHES ID and CHES party name can be multivalued, with pipe (|) being the separator.

@nljubesi, you could now take [ParlaMint-listOrg.tsv](https://github.com/clarin-eric/ParlaMint/blob/devel/Build/Metadata/ParlaMint-listOrg.tsv) and [ParlaMint-listOrg-en.tsv](https://github.com/clarin-eric/ParlaMint/blob/devel/Build/Metadata/ParlaMint-listOrg-en.tsv) as the new source, if this is still interesting for the proposed mapping.

Note, however, the the current TSV files were generated from the source TEI files as they were received from the partners, not the official buil, as that hasn't been made yet. I think there should be no differences, but one is never sure before actually running the build.

**Comment by nljubesi** [comment]
I can report that we have already used the list that has been proposed in https://github.com/clarin-eric/ParlaMint/issues/859#issuecomment-2021035182 and @matyaskopp  has enriched the list with PartyFacts IDs via Wikipedia IDs as these have the best coverage. @mmochtak is validating the list through analyses, and I hope that we will be ready to offer the PartyFacts IDs once this validation is through (a joint paper we are working on, so a few months).

If any activity on party mapping or description is planned on other sides, I suggest this is communicated here. We now have full coverage of ParlaMint 4.0, the dataset the current analyses are based on, and will not perform any further mappings before that research has been completed, i.e., these mapping has been validated.

**Comment by TomazErjavec** [comment]
Thanks @nljubesi for the report. By what you write we will not (be able to) add PartyFacts to ParlaMint 4.1, which is quite ok. 
This means we won't be doing any new party mappings now, and we will think about it again when doint 5.0
So, I will be closing this issue, and let's open a new one once this becomes current again.
