### ISSUE TITLE
Right-to-left script in ParlaMint

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#882]
This issue serves to report and discuss possible/existing problems with the encoding that are not documented or supported.

1) attribute `@join` in linguistic annotation. We support the value `right` which is problematic in right-to-left - do we want to introduce `join="left"`?
So we will have one value for left-to-right  languages (`right`) and one value for right-to-left languages (`left`) - which both mean: _the following token is joined to the current one_
The connllu format has a feature `noSpaceAfter` which clearly corresponds to left/right join.

@GiliGoldin, I am not sure if a sequence of word tokens in left-right order can appear in right-left text or if we can consider everything to be in right-to-left order if the language itself is written in right-to-left (we don't care about inside-token order there).

**Comment by GiliGoldin** [comment]
Yes, I agree that introducing join="left" for right-left languages like Hebrew would improve clarity and consistency, as join="right" assumes left-right logic. In right-left contexts, join="left" aligns naturally with "no space after" behavior. Embedded left-right segments (e.g., numbers, or Latin-script words ) can still appear, but I think they don’t typically affect the joining logic for tokens in Right-left text since these are often treated as separate tokens.

**Comment by TomazErjavec** [comment]
Sorry for not responding earier, in fact started writing but didn't finish. 
In short, yes, I'd also perfer join=right. Maybe the values should've been "prev" and "next".

How are tokens ordered in the .ana version? The same as in [CoNLL-U](https://github.com/UniversalDependencies/UD_Hebrew-HTB/blob/master/he_htb-ud-test.conllu)? Or, just the opposite, so that if you take away the markup, it's the same as the base text? This has been the assumption so far, but maybe not having to invert them is sensible?

**Comment by matyaskopp** [comment]
> How are tokens ordered in the .ana version? The same as in [CoNLL-U](https://github.com/UniversalDependencies/UD_Hebrew-HTB/blob/master/he_htb-ud-test.conllu)? Or, just the opposite, so that if you take away the markup, it's the same as the base text? This has been the assumption so far, but maybe not having to invert them is sensible?

The token order is in the order you read them, so it's the same as in the Conllu format. If I see it correctly (it is difficult for me to read the characters), the "disk/storage" order is similar for all versions: TEI, TEI.ana, and Conllu.
@GiliGoldin, correct me if I am wrong.

**Comment by GiliGoldin** [comment]
Yes you are correct.

**Comment by GiliGoldin** [comment]
> > How are tokens ordered in the .ana version? The same as in [CoNLL-U](https://github.com/UniversalDependencies/UD_Hebrew-HTB/blob/master/he_htb-ud-test.conllu)? Or, just the opposite, so that if you take away the markup, it's the same as the base text? This has been the assumption so far, but maybe not having to invert them is sensible?
> 
> The token order is in the order you read them, so it's the same as in the Conllu format. If I see it correctly (it is difficult for me to read the characters), the "disk/storage" order is similar for all versions: TEI, TEI.ana, and Conllu. @GiliGoldin, correct me if I am wrong.

Yes you are correct.

**Comment by TomazErjavec** [comment]
Great, one more worry less...

**Comment by matyaskopp** [comment]
Thanks for helping me clarify the situation: the right-to-left script is fine with the current encoding. 

Let this issue serve as documentation; we can extend the web documentation later if some find it useful.
